export interface DhikrItem {
  id: string;
  order: number;
  title: string;
  count: number;
  timeNote?: string;
  arabic: string;
  latin: string;
  translation: string;
  fadhilah?: string;
  dalil: string;
}

export interface IslamicModule {
  id: string;
  title: string;
  subtitle: string;
  badge: string;
  timeGuide: string;
  items: DhikrItem[];
}

// 1. DZIKIR PAGI SESUAI SUNNAH (Hisnul Muslim & Hadits Shahih)
export const morningDhikrModule: IslamicModule = {
  id: 'dzikir-pagi',
  title: 'Dzikir Pagi',
  subtitle: 'Subuh — Syuruq',
  badge: 'SESUAI SUNNAH',
  timeGuide: 'Waktu utama: Setelah shalat Subuh hingga matahari terbit. Boleh dibaca hingga menjelang waktu Dzuhur.',
  items: [
    {
      id: 'mp-01',
      order: 1,
      title: "Membaca Ta'awudz",
      count: 1,
      arabic: 'أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ',
      latin: "A'uudzu billaahi minasy syaithaanir rajiim",
      translation: 'Aku berlindung kepada Allah dari godaan syaitan yang terkutuk.',
      fadhilah: 'Membentengi diri dari godaan dan bisikan syaitan saat memulai dzikir dan tilawah.',
      dalil: 'QS. An-Nahl: 98',
    },
    {
      id: 'mp-02',
      order: 2,
      title: 'Membaca Ayat Kursi',
      count: 1,
      arabic: 'اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَّهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ ۗ مَن ذَا الَّذِي يَشْفَعُ عِندَهُ إِلَّا بِإِذْنِهِ ۚ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ ۖ وَلَا يُحِيطُونَ بِشَيْءٍ مِّنْ عِلْمِهِ إِلَّا بِمَا شَاءَ ۚ وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالْأَرْضَ ۖ وَلَا يَئُودُهُ حِفْظُهُمَا ۚ وَهُوَ الْعَلِيُّ الْعَظِيمُ',
      latin: "Allaahu laa ilaaha illaa huwal hayyul qayyuum, laa ta'khudzuhuu sinatuw wa laa naum, lahuu maa fis samaawaati wa maa fil ardh, man dzalladzii yasyfa'u 'indahuu illaa bi-idznih, ya'lamu maa baina aidiihim wa maa khalfahum, wa laa yuhiithuuna bi syai-im min 'ilmihii illaa bimaa syaa', wasi'a kursiyyuhus samaawaati wal ardh, wa laa ya-uuduhuu hifzhuhumaa, wa huwal 'aliyyul 'azhiim.",
      translation: 'Allah, tidak ada Tuhan (yang berhak disembah) melainkan Dia Yang Hidup kekal lagi terus-menerus mengurus (makhluk-Nya); tidak mengantuk dan tidak tidur. Kepunyaan-Nya apa yang di langit dan di bumi. Tiada yang dapat memberi syafaat di sisi Allah tanpa izin-Nya? Allah mengetahui apa-apa yang di hadapan mereka dan di belakang mereka, dan mereka tidak mengetahui apa-apa dari ilmu Allah melainkan apa yang dikehendaki-Nya. Kursi Allah meliputi langit dan bumi. Dan Allah tidak merasa berat memelihara keduanya, dan Allah Maha Tinggi lagi Maha Besar.',
      fadhilah: 'Siapa yang membacanya di pagi hari akan dilindungi dari gangguan jin dan setan hingga petang hari.',
      dalil: 'HR. An-Nasa’i dalam Amalul Yaum wal Lailah no. 100, dishahihkan oleh Al-Albani.',
    },
    {
      id: 'mp-03',
      order: 3,
      title: 'Membaca Surat Al-Ikhlas',
      count: 3,
      arabic: 'بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ\nقُلْ هُوَ اللَّهُ أَحَدٌ ۞ اللَّهُ الصَّمَدُ ۞ لَمْ يَلِدْ وَلَمْ يُولَدْ ۞ وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ',
      latin: 'Bismillaahir rahmaanir rahiim. Qul huwallaahu ahad. Allaahush shamad. Lam yalid wa lam yuulad. Wa lam yakul lahuu kufuwan ahad.',
      translation: 'Dengan nama Allah Yang Maha Pengasih, Maha Penyayang. Katakanlah (Muhammad), "Dialah Allah, Yang Maha Esa. Allah tempat meminta segala sesuatu. (Allah) tidak beranak dan tidak pula diperanakkan. Dan tidak ada sesuatu pun yang setara dengan Dia."',
      fadhilah: 'Rasulullah ﷺ bersabda: "Katakanlah Qul Huwallahu Ahad dan Mu\'awwidzatain (Al-Falaq dan An-Nas) saat petang dan pagi hari sebanyak tiga kali, niscaya mencukupkanmu dari segala sesuatu."',
      dalil: 'HR. Abu Dawud no. 5082 dan At-Tirmidzi no. 3575, dinilai Hasan Shahih.',
    },
    {
      id: 'mp-04',
      order: 4,
      title: 'Membaca Surat Al-Falaq',
      count: 3,
      arabic: 'بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ\nقُلْ أَعُوذُ بِرَبِّ الْفَلَقِ ۞ مِن شَرِّ مَا خَلَقَ ۞ وَمِن شَرِّ غَاسِقٍ إِذَا وَقَبَ ۞ وَمِن شَرِّ النَّفَّاثَاتِ فِي الْعُقَدِ ۞ وَمِن شَرِّ حَاسِدٍ إِذَا حَسَدَ',
      latin: "Bismillaahir rahmaanir rahiim. Qul a'uudzu birabbil falaq. Min syarri maa khalaq. Wa min syarri ghaasiqin idzaa waqab. Wa min syarrin naffaatsaati fil 'uqad. Wa min syarri haasidin idzaa hasad.",
      translation: 'Dengan nama Allah Yang Maha Pengasih, Maha Penyayang. Katakanlah, "Aku berlindung kepada Tuhan yang menguasai subuh (fajar), dari kejahatan makhluk yang Dia ciptakan, dan dari kejahatan malam apabila telah gelap gulita, dan dari kejahatan (perempuan-perempuan) penyihir yang meniup pada buhul-buhul (talinya), dan dari kejahatan orang yang dengki apabila dia dengki."',
      fadhilah: 'Surat perlindungan utama dari kejahatan malam, sihir, dengki, dan kejahatan seluruh makhluk.',
      dalil: 'HR. Abu Dawud no. 5082 dan At-Tirmidzi no. 3575.',
    },
    {
      id: 'mp-05',
      order: 5,
      title: 'Membaca Surat An-Nas',
      count: 3,
      arabic: 'بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ\nقُلْ أَعُوذُ بِرَبِّ النَّاسِ ۞ مَلِكِ النَّاسِ ۞ إِلَٰهِ النَّاسِ ۞ مِن شَرِّ الْوَسْوَاسِ الْخَنَّاسِ ۞ الَّذِي يُوَسْوِسُ فِي صُدُورِ النَّاسِ ۞ مِنَ الْجِنَّةِ وَالنَّاسِ',
      latin: "Bismillaahir rahmaanir rahiim. Qul a'uudzu birabbin naas. Malikin naas. Ilaahin naas. Min syarril waswaasil khannaas. Alladzii yuwaswisu fii shuduurin naas. Minal jinnati wan naas.",
      translation: 'Dengan nama Allah Yang Maha Pengasih, Maha Penyayang. Katakanlah, "Aku berlindung kepada Tuhannya manusia, Raja manusia, Sembahan manusia, dari kejahatan (bisikan) setan yang bersembunyi, yang membisikkan (kejahatan) ke dalam dada manusia, dari (golongan) jin dan manusia."',
      fadhilah: 'Surat perlindungan utama dari bisikan dan tipu daya setan, jin, serta manusia.',
      dalil: 'HR. Abu Dawud no. 5082 dan At-Tirmidzi no. 3575.',
    },
    {
      id: 'mp-06',
      order: 6,
      title: 'Dzikir Memasuki Waktu Pagi',
      count: 1,
      arabic: 'أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لاَ إِلَـهَ إِلاَّ اللَّهُ وَحْدَهُ لاَ شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ. رَبِّ أَسْأَلُكَ خَيْرَ مَا فِي هَـذَا الْيَوْمِ وَخَيْرَ مَا بَعْدَهُ، وَأَعُوذُ بِكَ مِنْ شَرِّ مَا فِي هَـذَا الْيَوْمِ وَشَرِّ مَا بَعْدَهُ، رَبِّ أَعُوذُ بِكَ مِنَ الْكَسَلِ وَسُوءِ الْكِبَرِ، رَبِّ أَعُوذُ بِكَ مِنْ عَذَابٍ فِي النَّارِ وَعَذَابٍ فِي الْقَبْرِ',
      latin: "Ashbahnaa wa ashbahal mulku lillaah, walhamdulillaah, laa ilaaha illallaahu wahdahu laa syariika lah, lahul mulku wa lahul hamdu wa huwa 'alaa kulli syai-in qadiir. Rabbi as-aluka khaira maa fii haadzal yaumi wa khaira maa ba'dah, wa a'uudzu bika min syarri maa fii haadzal yaumi wa syarri maa ba'dah. Rabbi a'uudzu bika minal kasali wa suu-il kibar, rabbi a'uudzu bika min 'adzaabin fin naari wa 'adzaabin fil qabr.",
      translation: 'Kami telah memasuki waktu pagi dan kerajaan hanya milik Allah, segala puji bagi Allah. Tidak ada Tuhan yang berhak disembah selain Allah semata, tiada sekutu bagi-Nya. Milik-Nya kerajaan dan bagi-Nya pujian, dan Dia Maha Kuasa atas segala sesuatu. Wahai Tuhanku, aku memohon kepada-Mu kebaikan pada hari ini dan kebaikan setelahnya, dan aku berlindung kepada-Mu dari keburukan pada hari ini dan keburukan setelahnya. Wahai Tuhanku, aku berlindung kepada-Mu dari kemalasan dan keburukan di hari tua. Wahai Tuhanku, aku berlindung kepada-Mu dari siksa neraka dan siksa kubur.',
      fadhilah: 'Menyerahkan kepemilikan hari hanya kepada Allah dan memohon perlindungan dari kemalasan serta siksa kubur.',
      dalil: 'HR. Muslim no. 2723.',
    },
    {
      id: 'mp-07',
      order: 7,
      title: 'Sayyidul Istighfar (Penghulu Istighfar)',
      count: 1,
      arabic: 'اللَّهُمَّ أَنْتَ رَبِّي لاَ إِلَـهَ إِلاَّ أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ، وَأَبُوءُ بِذَنْبِي فَاغْفِرْ لِي فَإِنَّهُ لاَ يَغْفِرُ الذُّنُوبَ إِلاَّ أَنْتَ',
      latin: "Allahumma anta rabbii laa ilaaha illaa anta, khalaqtanii wa anaa 'abduka, wa anaa 'alaa 'ahdika wa wa'dika mastatha'tu, a'uudzu bika min syarri maa shana'tu, abuu-u laka bini'matika 'alayya, wa abuu-u bi dzanbii faghfir lii fa innahuu laa yaghfirudz dzunuuba illaa anta.",
      translation: 'Ya Allah, Engkau adalah Tuhanku, tidak ada Tuhan yang berhak disembah kecuali Engkau. Engkaulah yang menciptakanku dan aku adalah hamba-Mu. Aku akan setia pada janji-Mu semampuku. Aku berlindung kepada-Mu dari keburukan apa yang telah kuperbuat. Aku mengakui nikmat-Mu kepadaku dan aku mengakui dosaku kepada-Mu, maka ampunilah aku. Karena sesungguhnya tiada yang dapat mengampuni dosa-dosa kecuali Engkau.',
      fadhilah: 'Rasulullah ﷺ bersabda: "Barangsiapa mengucapkannya di waktu pagi dengan penuh keyakinan, lalu ia meninggal pada hari itu sebelum petang, niscaya ia termasuk penghuni surga."',
      dalil: 'HR. Bukhari no. 6306.',
    },
    {
      id: 'mp-08',
      order: 8,
      title: 'Doa Permohonan Keselamatan Jasmani & Agama',
      count: 3,
      arabic: 'اللَّهُمَّ عَافِنِي فِي بَدَنِي، اللَّهُمَّ عَافِنِي فِي سَمْعِي، اللَّهُمَّ عَافِنِي فِي بَصَرِي، لاَ إِلَـهَ إِلاَّ أَنْتَ. اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْكُفْرِ وَالْفَقْرِ، وَأَعُوذُ بِكَ مِنْ عَذَابِ الْقَبْرِ، لاَ إِلَـهَ إِلاَّ أَنْتَ',
      latin: "Allahumma 'aafinii fii badanii, Allahumma 'aafinii fii sam'ii, Allahumma 'aafinii fii basharii, laa ilaaha illaa anta. Allahumma innii a'uudzu bika minal kufri wal faqr, wa a'uudzu bika min 'adzaabil qabr, laa ilaaha illaa anta.",
      translation: 'Ya Allah, selamatkanlah tubuhku (dari penyakit dan maksiat). Ya Allah, selamatkanlah pendengaranku. Ya Allah, selamatkanlah penglihatanku. Tidak ada Tuhan yang berhak disembah selain Engkau. Ya Allah, sesungguhnya aku berlindung kepada-Mu dari kekufuran dan kefakiran. Dan aku berlindung kepada-Mu dari siksa kubur. Tidak ada Tuhan selain Engkau.',
      fadhilah: 'Menjaga kesehatan panca indera, keimanan, dan terhindar dari himpitan kefakiran.',
      dalil: 'HR. Abu Dawud no. 5090 dan Ahmad, sanadnya Hasan.',
    },
    {
      id: 'mp-09',
      order: 9,
      title: 'Doa Memohon Ampunan dan Perlindungan Menyeluruh',
      count: 1,
      arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَفْوَ وَالْعَافِيَةَ فِي الدُّنْيَا وَالآخِرَةِ، اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَفْوَ وَالْعَافِيَةَ فِي دِينِي وَدُنْيَايَ وَأَهْلِي وَمَالِي، اللَّهُمَّ اسْتُرْ عَوْرَاتِي وَآمِنْ رَوْعَاتِي، اللَّهُمَّ احْفَظْنِي مِنْ بَيْنِ يَدَيَّ، وَمِنْ خَلْفِي، وَعَنْ يَمِينِي، وَعَنْ شِمَالِي، وَمِنْ فَوْقِي، وَأَعُوذُ بِعَظَمَتِكَ أَنْ أُغْتَالَ مِنْ تَحْتِي',
      latin: "Allahumma innii as-alukal 'afwa wal 'aafiyah fid dunyaa wal aakhirah. Allahumma innii as-alukal 'afwa wal 'aafiyah fii diinii wa dunyaaya wa ahlii wa maalii. Allahummastur 'auraatii wa aamin rau'aatii. Allahummahfazhnii min baini yadayya, wa min khalfii, wa 'an yamiinii, wa 'an syimaalii, wa min fauqii, wa a'uudzu bi'azhamatika an ughtaala min tahtii.",
      translation: 'Ya Allah, sesungguhnya aku memohon ampunan dan keselamatan di dunia dan akhirat. Ya Allah, aku memohon ampunan dan keselamatan dalam agamaku, duniaku, keluargaku, dan hartaku. Ya Allah, tutuplah aib-aibku dan tenteramkanlah rasa takutku. Ya Allah, peliharalah aku dari arah depanku, belakangku, kananku, kiriku, dan dari atasku. Dan aku berlindung dengan keagungan-Mu agar tidak disambar dari bawahku.',
      fadhilah: 'Perlindungan dari bencana enam arah yang tidak pernah ditinggalkan Rasulullah ﷺ setiap pagi dan petang.',
      dalil: 'HR. Abu Dawud no. 5074 dan Ibnu Majah no. 3871, dinilai Shahih.',
    },
    {
      id: 'mp-10',
      order: 10,
      title: 'Doa Perlindungan dari Bahaya Alam Semesta',
      count: 3,
      arabic: 'بِسْمِ اللَّهِ الَّذِي لاَ يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الأَرْضِ وَلاَ فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ',
      latin: "Bismillaahilladzii laa yadhurru ma'asmihii syai-un fil ardhi wa laa fis samaa-i wa huwas samii'ul 'aliim.",
      translation: 'Dengan nama Allah yang bersama nama-Nya tidak ada sesuatu pun di bumi maupun di langit yang dapat membahayakan, dan Dia Maha Mendengar lagi Maha Mengetahui.',
      fadhilah: 'Rasulullah ﷺ bersabda: "Siapa yang membacanya tiga kali di pagi dan petang hari, tidak akan ada marabahaya yang dapat menimpanya."',
      dalil: 'HR. Abu Dawud no. 5088 dan At-Tirmidzi no. 3388, dinilai Hasan Shahih.',
    },
    {
      id: 'mp-11',
      order: 11,
      title: 'Keridhaan kepada Allah, Islam, dan Nabi ﷺ',
      count: 3,
      arabic: 'رَضِيتُ بِاللَّهِ رَبًّا، وَبِالإِسْلاَمِ دِينًا، وَبِمُحَمَّدٍ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ نَبِيًّا',
      latin: "Radhiitu billaahi rabbaa, wa bil Islaami diinaa, wa bi Muhammadin shallallaahu 'alaihi wa sallama nabiyyaa.",
      translation: 'Aku ridha Allah sebagai Tuhanku, Islam sebagai agamaku, dan Muhammad ﷺ sebagai nabiku.',
      fadhilah: 'Barangsiapa membacanya di waktu pagi dan petang sebanyak 3 kali, menjadi hak Allah untuk membuatnya ridha dan memasukkannya ke dalam surga.',
      dalil: 'HR. Abu Dawud no. 5072 dan At-Tirmidzi no. 3389, hadits Hasan.',
    },
    {
      id: 'mp-12',
      order: 12,
      title: 'Doa Memohon Perbaikan Segala Urusan',
      count: 1,
      arabic: 'يَا حَيُّ يَا قَيُّومُ بِرَحْمَتِكَ أَسْتَغِيثُ، أَصْلِحْ لِي شَأْنِي كُلَّهُ، وَلاَ تَكِلْنِي إِلَى نَفْسِي طَرْفَةَ عَيْنٍ',
      latin: "Yaa Hayyu Yaa Qayyuum, bi rahmatika astaghiits, ashlih lii sya'nii kullah, wa laa takilnii ilaa nafsii tharfata 'ain.",
      translation: 'Wahai Yang Maha Hidup, Wahai Yang Terus-menerus Mengurus makhluk-Nya, dengan rahmat-Mu aku memohon pertolongan. Perbaikilah seluruh urusanku, dan janganlah Engkau serahkan aku kepada diriku sendiri walau sekejap mata.',
      fadhilah: 'Doa yang diwasiatkan Rasulullah ﷺ kepada putrinya Fathimah radhiyallahu \'anha setiap pagi dan petang.',
      dalil: 'HR. An-Nasa’i dalam As-Sunan Al-Kubra no. 10405 dan Al-Hakim 1/545, Hasan.',
    },
    {
      id: 'mp-13',
      order: 13,
      title: 'Tasbih dan Tahmid 100 Kali',
      count: 100,
      arabic: 'سُبْحَانَ اللَّهِ وَبِحَمْدِهِ',
      latin: 'Subhaanallaahi wa bihamdihi.',
      translation: 'Maha Suci Allah dan segala puji bagi-Nya.',
      fadhilah: 'Rasulullah ﷺ bersabda: "Barangsiapa membaca Subhanallah wa bihamdihi 100 kali sehari, dosanya akan diampuni meskipun sebanyak buih di lautan."',
      dalil: 'HR. Bukhari no. 6405 dan Muslim no. 2691.',
    },
    {
      id: 'mp-14',
      order: 14,
      title: 'Tahlil Pengesaan Allah',
      count: 10,
      arabic: 'لاَ إِلَـهَ إِلاَّ اللَّهُ وَحْدَهُ لاَ شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ، وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ',
      latin: "Laa ilaaha illallaahu wahdahu laa syariika lah, lahul mulku wa lahul hamdu, wa huwa 'alaa kulli syai-in qadiir.",
      translation: 'Tidak ada Tuhan yang berhak disembah selain Allah semata, tidak ada sekutu bagi-Nya. Bagi-Nya kerajaan dan bagi-Nya segala pujian, dan Dia Maha Kuasa atas segala sesuatu.',
      fadhilah: 'Membacanya 10 kali bagaikan memerdekakan empat orang budak dari keturunan Nabi Ismail ‘alaihissalam.',
      dalil: 'HR. Bukhari no. 6404 dan Muslim no. 2693.',
    },
    {
      id: 'mp-15',
      order: 15,
      title: 'Doa Memohon Ilmu, Rezeki, dan Amal Diterima',
      count: 1,
      arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ عِلْمًا نَافِعًا، وَرِزْقًا طَيِّبًا، وَعَمَلاً مُتَقَبَّلاً',
      latin: "Allahumma innii as-aluka 'ilman naafi'aa, wa rizqan thayyibaa, wa 'amalan mutaqabbalaa.",
      translation: 'Ya Allah, sesungguhnya aku memohon kepada-Mu ilmu yang bermanfaat, rezeki yang halal dan baik, serta amal yang diterima.',
      fadhilah: 'Dibaca Nabi ﷺ setiap pagi setelah salam shalat Subuh untuk mengawali aktivitas harian.',
      dalil: 'HR. Ibnu Majah no. 925 dan Ahmad 6/305, dinilai Shahih.',
    },
  ],
};

// 2. DZIKIR PETANG SESUAI SUNNAH
export const eveningDhikrModule: IslamicModule = {
  id: 'dzikir-petang',
  title: 'Dzikir Petang',
  subtitle: 'Ashar — Maghrib',
  badge: 'SESUAI SUNNAH',
  timeGuide: 'Waktu utama: Setelah shalat Ashar hingga tenggelam matahari (Maghrib). Boleh dibaca hingga menjelang waktu Isya.',
  items: [
    {
      id: 'ep-01',
      order: 1,
      title: "Membaca Ta'awudz",
      count: 1,
      arabic: 'أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ',
      latin: "A'uudzu billaahi minasy syaithaanir rajiim",
      translation: 'Aku berlindung kepada Allah dari godaan syaitan yang terkutuk.',
      fadhilah: 'Perlindungan dari kejahatan setan yang mulai bertebaran saat petang hari menjelang malam.',
      dalil: 'QS. An-Nahl: 98',
    },
    {
      id: 'ep-02',
      order: 2,
      title: 'Membaca Ayat Kursi',
      count: 1,
      arabic: 'اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَّهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ ۗ مَن ذَا الَّذِي يَشْفَعُ عِندَهُ إِلَّا بِإِذْنِهِ ۚ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ ۖ وَلَا يُحِيطُونَ بِشَيْءٍ مِّنْ عِلْمِهِ إِلَّا بِمَا شَاءَ ۚ وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالْأَرْضَ ۖ وَلَا يَئُودُهُ حِفْظُهُمَا ۚ وَهُوَ الْعَلِيُّ الْعَظِيمُ',
      latin: "Allaahu laa ilaaha illaa huwal hayyul qayyuum, laa ta'khudzuhuu sinatuw wa laa naum...",
      translation: 'Allah, tidak ada Tuhan yang berhak disembah melainkan Dia Yang Hidup kekal lagi terus-menerus mengurus makhluk-Nya...',
      fadhilah: 'Siapa yang membacanya di petang hari akan dilindungi dari gangguan jin dan setan hingga waktu pagi.',
      dalil: 'HR. An-Nasa’i dalam Amalul Yaum wal Lailah no. 100.',
    },
    {
      id: 'ep-03',
      order: 3,
      title: 'Membaca Surat Al-Ikhlas',
      count: 3,
      arabic: 'بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ\nقُلْ هُوَ اللَّهُ أَحَدٌ ۞ اللَّهُ الصَّمَدُ ۞ لَمْ يَلِدْ وَلَمْ يُولَدْ ۞ وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ',
      latin: 'Bismillaahir rahmaanir rahiim. Qul huwallaahu ahad. Allaahush shamad. Lam yalid wa lam yuulad. Wa lam yakul lahuu kufuwan ahad.',
      translation: 'Dengan nama Allah Yang Maha Pengasih, Maha Penyayang. Katakanlah (Muhammad), "Dialah Allah, Yang Maha Esa. Allah tempat meminta segala sesuatu. (Allah) tidak beranak dan tidak pula diperanakkan. Dan tidak ada sesuatu pun yang setara dengan Dia."',
      fadhilah: 'Mencukupkan seorang hamba dari segala marabahaya dan kejahatan makhluk di malam hari.',
      dalil: 'HR. Abu Dawud no. 5082 dan At-Tirmidzi no. 3575, dinilai Hasan Shahih.',
    },
    {
      id: 'ep-04',
      order: 4,
      title: 'Membaca Surat Al-Falaq',
      count: 3,
      arabic: 'بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ\nقُلْ أَعُوذُ بِرَبِّ الْفَلَقِ ۞ مِن شَرِّ مَا خَلَقَ ۞ وَمِن شَرِّ غَاسِقٍ إِذَا وَقَبَ ۞ وَمِن شَرِّ النَّفَّاثَاتِ فِي الْعُقَدِ ۞ وَمِن شَرِّ حَاسِدٍ إِذَا حَسَدَ',
      latin: "Bismillaahir rahmaanir rahiim. Qul a'uudzu birabbil falaq. Min syarri maa khalaq. Wa min syarri ghaasiqin idzaa waqab. Wa min syarrin naffaatsaati fil 'uqad. Wa min syarri haasidin idzaa hasad.",
      translation: 'Dengan nama Allah Yang Maha Pengasih, Maha Penyayang. Katakanlah, "Aku berlindung kepada Tuhan yang menguasai subuh (fajar), dari kejahatan makhluk yang Dia ciptakan, dan dari kejahatan malam apabila telah gelap gulita, dan dari kejahatan (perempuan-perempuan) penyihir yang meniup pada buhul-buhul (talinya), dan dari kejahatan orang yang dengki apabila dia dengki."',
      fadhilah: 'Benteng perlindungan dari kegelapan malam, sihir, kedengkian, dan kejahatan makhluk.',
      dalil: 'HR. Abu Dawud no. 5082 dan At-Tirmidzi no. 3575.',
    },
    {
      id: 'ep-05',
      order: 5,
      title: 'Membaca Surat An-Nas',
      count: 3,
      arabic: 'بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ\nقُلْ أَعُوذُ بِرَبِّ النَّاسِ ۞ مَلِكِ النَّاسِ ۞ إِلَٰهِ النَّاسِ ۞ مِن شَرِّ الْوَسْوَاسِ الْخَنَّاسِ ۞ الَّذِي يُوَسْوِسُ فِي صُدُورِ النَّاسِ ۞ مِنَ الْجِنَّةِ وَالنَّاسِ',
      latin: "Bismillaahir rahmaanir rahiim. Qul a'uudzu birabbin naas. Malikin naas. Ilaahin naas. Min syarril waswaasil khannaas. Alladzii yuwaswisu fii shuduurin naas. Minal jinnati wan naas.",
      translation: 'Dengan nama Allah Yang Maha Pengasih, Maha Penyayang. Katakanlah, "Aku berlindung kepada Tuhannya manusia, Raja manusia, Sembahan manusia, dari kejahatan (bisikan) setan yang bersembunyi, yang membisikkan (kejahatan) ke dalam dada manusia, dari (golongan) jin dan manusia."',
      fadhilah: 'Perlindungan dari bisikan dan was-was setan serta godaan jin dan manusia di malam hari.',
      dalil: 'HR. Abu Dawud no. 5082 dan At-Tirmidzi no. 3575.',
    },
    {
      id: 'ep-06',
      order: 6,
      title: 'Dzikir Memasuki Waktu Petang',
      count: 1,
      arabic: 'أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لاَ إِلَـهَ إِلاَّ اللَّهُ وَحْدَهُ لاَ شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ. رَبِّ أَسْأَلُكَ خَيْرَ مَا فِي هَـذِهِ اللَّيْلَةِ وَخَيْرَ مَا بَعْدَهَا، وَأَعُوذُ بِكَ مِنْ شَرِّ مَا فِي هَـذِهِ اللَّيْلَةِ وَشَرِّ مَا بَعْدَهَا، رَبِّ أَعُوذُ بِكَ مِنَ الْكَسَلِ وَسُوءِ الْكِبَرِ، رَبِّ أَعُوذُ بِكَ مِنْ عَذَابٍ فِي النَّارِ وَعَذَابٍ فِي الْقَبْرِ',
      latin: "Amsainaa wa amsal mulku lillaah, walhamdulillaah, laa ilaaha illallaahu wahdahu laa syariika lah, lahul mulku wa lahul hamdu wa huwa 'alaa kulli syai-in qadiir. Rabbi as-aluka khaira maa fii haadzihil lailati wa khaira maa ba'dahaa, wa a'uudzu bika min syarri maa fii haadzihil lailati wa syarri maa ba'dahaa. Rabbi a'uudzu bika minal kasali wa suu-il kibar, rabbi a'uudzu bika min 'adzaabin fin naari wa 'adzaabin fil qabr.",
      translation: 'Kami telah memasuki waktu petang dan kerajaan hanya milik Allah, segala puji bagi Allah. Tidak ada Tuhan yang berhak disembah selain Allah semata, tiada sekutu bagi-Nya. Milik-Nya kerajaan dan bagi-Nya pujian, dan Dia Maha Kuasa atas segala sesuatu. Wahai Tuhanku, aku memohon kepada-Mu kebaikan malam ini dan kebaikan setelahnya, dan aku berlindung kepada-Mu dari keburukan malam ini dan keburukan setelahnya...',
      fadhilah: 'Memohon perlindungan dari kejahatan malam, kemalasan, dan siksa kubur.',
      dalil: 'HR. Muslim no. 2723.',
    },
    {
      id: 'ep-07',
      order: 7,
      title: 'Sayyidul Istighfar',
      count: 1,
      arabic: 'اللَّهُمَّ أَنْتَ رَبِّي لاَ إِلَـهَ إِلاَّ أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ، وَأَبُوءُ بِذَنْبِي فَاغْفِرْ لِي فَإِنَّهُ لاَ يَغْفِرُ الذُّنُوبَ إِلاَّ أَنْتَ',
      latin: "Allahumma anta rabbii laa ilaaha illaa anta, khalaqtanii wa anaa 'abduka, wa anaa 'alaa 'ahdika wa wa'dika mastatha'tu, a'uudzu bika min syarri maa shana'tu, abuu-u laka bini'matika 'alayya, wa abuu-u bi dzanbii faghfir lii fa innahuu laa yaghfirudz dzunuuba illaa anta.",
      translation: 'Ya Allah, Engkau adalah Tuhanku, tidak ada Tuhan selain Engkau. Engkaulah yang menciptakanku dan aku hamba-Mu...',
      fadhilah: 'Barangsiapa membacanya di petang hari dengan penuh keyakinan lalu meninggal di malam hari, ia termasuk penghuni surga.',
      dalil: 'HR. Bukhari no. 6306.',
    },
    {
      id: 'ep-08',
      order: 8,
      title: 'Doa Perlindungan dengan Kalimat Allah yang Sempurna',
      count: 3,
      arabic: 'أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ',
      latin: "A'uudzu bi kalimaatillaahit taammaati min syarri maa khalaq.",
      translation: 'Aku berlindung dengan kalimat-kalimat Allah yang sempurna dari kejahatan apa yang telah Dia ciptakan.',
      fadhilah: 'Rasulullah ﷺ bersabda: "Siapa yang membacanya tiga kali di waktu petang, tidak akan ada sengatan atau racun binatang berbisa yang dapat memudharatkannya di malam itu."',
      dalil: 'HR. Muslim no. 2709.',
    },
    {
      id: 'ep-09',
      order: 9,
      title: 'Doa Perlindungan dari Bahaya Alam Semesta',
      count: 3,
      arabic: 'بِسْمِ اللَّهِ الَّذِي لاَ يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الأَرْضِ وَلاَ فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ',
      latin: "Bismillaahilladzii laa yadhurru ma'asmihii syai-un fil ardhi wa laa fis samaa-i wa huwas samii'ul 'aliim.",
      translation: 'Dengan nama Allah yang bersama nama-Nya tidak ada sesuatu pun di bumi maupun di langit yang dapat membahayakan, dan Dia Maha Mendengar lagi Maha Mengetahui.',
      fadhilah: 'Perlindungan dari marabahaya tiba-tiba hingga pagi menjelang.',
      dalil: 'HR. Abu Dawud no. 5088 dan At-Tirmidzi no. 3388.',
    },
    {
      id: 'ep-10',
      order: 10,
      title: 'Keridhaan kepada Allah, Islam, dan Nabi ﷺ',
      count: 3,
      arabic: 'رَضِيتُ بِاللَّهِ رَبًّا، وَبِالإِسْلاَمِ دِينًا، وَبِمُحَمَّدٍ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ نَبِيًّا',
      latin: "Radhiitu billaahi rabbaa, wa bil Islaami diinaa, wa bi Muhammadin shallallaahu 'alaihi wa sallama nabiyyaa.",
      translation: 'Aku ridha Allah sebagai Tuhanku, Islam sebagai agamaku, dan Muhammad ﷺ sebagai nabiku.',
      fadhilah: 'Allah menjanjikan keridhaan-Nya bagi hamba yang mengucapkannya dengan tulus.',
      dalil: 'HR. Abu Dawud no. 5072 dan At-Tirmidzi no. 3389.',
    },
    {
      id: 'ep-11',
      order: 11,
      title: 'Tasbih dan Tahmid 100 Kali',
      count: 100,
      arabic: 'سُبْحَانَ اللَّهِ وَبِحَمْدِهِ',
      latin: 'Subhaanallaahi wa bihamdihi.',
      translation: 'Maha Suci Allah dan segala puji bagi-Nya.',
      fadhilah: 'Tidak ada seorang pun pada hari kiamat yang membawa amalan lebih utama darinya kecuali orang yang membaca semisalnya atau lebih banyak.',
      dalil: 'HR. Muslim no. 2692.',
    },
  ],
};

// 3. DZIKIR BA'DA SHOLAT SESUAI SUNNAH
export const afterPrayerDhikrModule: IslamicModule = {
  id: 'bada-sholat',
  title: "Dzikir Ba'da Sholat",
  subtitle: 'Setelah Shalat Fardhu',
  badge: 'SESUAI SUNNAH',
  timeGuide: 'Dibaca tepat setelah selesai melaksanakan shalat fardhu lima waktu, sebelum berpindah atau beranjak dari tempat shalat.',
  items: [
    {
      id: 'bp-01',
      order: 1,
      title: 'Membaca Istighfar 3x & Doa Keselamatan',
      count: 3,
      arabic: 'أَسْتَغْفِرُ اللَّهَ (٣×)\n\nاللَّهُمَّ أَنْتَ السَّلاَمُ، وَمِنْكَ السَّلاَمُ، تَبَارَكْتَ يَا ذَا الْجَلاَلِ وَالإِكْرَامِ',
      latin: "Astaghfirullah (3x).\n\nAllahumma antas salaam wa minkas salaam, tabaarakta yaa dzal jalaali wal ikraam.",
      translation: 'Aku memohon ampun kepada Allah (3 kali).\n\nYa Allah, Engkaulah As-Salam (Yang Selamat dari segala aib), dan dari-Mu lah segala keselamatan. Maha Berkah Engkau, wahai Dzat Pemilik Keagungan dan Kemuliaan.',
      fadhilah: 'Rasulullah ﷺ apabila selesai dari shalatnya senantiasa beristighfar tiga kali dan membaca doa ini.',
      dalil: 'HR. Muslim no. 591 dari Tsauban radhiyallahu ‘anhu.',
    },
    {
      id: 'bp-02',
      order: 2,
      title: 'Tahlil & Doa Ketetapan Takdir',
      count: 1,
      arabic: 'لاَ إِلَـهَ إِلاَّ اللَّهُ وَحْدَهُ لاَ شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ، اللَّهُمَّ لاَ مَانِعَ لِمَا أَعْطَيْتَ، وَلاَ مُعْطِيَ لِمَا مَنَعْتَ، وَلاَ يَنْفَعُ ذَا الْجَدِّ مِنْكَ الْجَدُّ',
      latin: "Laa ilaaha illallaahu wahdahu laa syariika lah, lahul mulku wa lahul hamdu wa huwa 'alaa kulli syai-in qadiir. Allahumma laa maani'a limaa a'thaita, wa laa mu'thiya limaa mana'ta, wa laa yanfa'u dzal jaddi minkal jaddu.",
      translation: 'Tiada Tuhan selain Allah Yang Maha Esa, tiada sekutu bagi-Nya. Milik-Nya kerajaan dan bagi-Nya segala puji, dan Dia Maha Kuasa atas segala sesuatu. Ya Allah, tidak ada yang dapat menghalangi apa yang Engkau berikan, dan tidak ada yang dapat memberi apa yang Engkau halangi, serta tidak bermanfaat kekayaan dan kedudukan seseorang di hadapan-Mu.',
      fadhilah: 'Mu’awiyah radhiyallahu ‘anhu menulis surat bahwa Nabi ﷺ senantiasa mengucapkannya selesai shalat fardhu.',
      dalil: 'HR. Bukhari no. 844 dan Muslim no. 593.',
    },
    {
      id: 'bp-03',
      order: 3,
      title: 'Tahlil Pengagungan & Pemurnian Ibadah',
      count: 1,
      arabic: 'لاَ إِلَـهَ إِلاَّ اللَّهُ وَحْدَهُ لاَ شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ. لاَ حَوْلَ وَلاَ قُوَّةَ إِلاَّ بِاللَّهِ، لاَ إِلَـهَ إِلاَّ اللَّهُ، وَلاَ نَعْبُدُ إِلاَّ إِيَّاهُ، لَهُ النِّعْمَةُ وَلَهُ الْفَضْلُ وَلَهُ الثَّنَاءُ الْحَسَنُ، لاَ إِلَـهَ إِلاَّ اللَّهُ مُخْلِصِينَ لَهُ الدِّينَ وَلَوْ كَرِهَ الْكَافِرُونَ',
      latin: "Laa ilaaha illallaahu wahdahu laa syariika lah, lahul mulku wa lahul hamdu wa huwa 'alaa kulli syai-in qadiir. Laa hawla wa laa quwwata illaa billaah. Laa ilaaha illallaah, wa laa na'budu illaa iyyaah, lahun ni'matu wa lahul fadhlu wa lahuts tsanaa-ul hasan. Laa ilaaha illallaahu mukhlishiina lahud diina wa lau karihal kaafiruun.",
      translation: 'Tiada Tuhan selain Allah Yang Maha Esa, tiada sekutu bagi-Nya... Tiada daya dan upaya kecuali dengan pertolongan Allah. Tiada sesembahan yang berhak disembah selain Allah, dan kami tidak beribadah kecuali kepada-Nya. Milik-Nya kenikmatan, karunia, dan sanjungan yang agung...',
      fadhilah: 'Abdullah bin Az-Zubair radhiyallahu ‘anhuma bertahlil dengan kalimat ini setiap selesai shalat sebagaimana Nabi ﷺ.',
      dalil: 'HR. Muslim no. 594.',
    },
    {
      id: 'bp-04',
      order: 4,
      title: 'Tasbih (Subhanallah)',
      count: 33,
      arabic: 'سُبْحَانَ اللَّهِ',
      latin: 'Subhaanallaah',
      translation: 'Maha Suci Allah.',
      fadhilah: 'Bagian dari tasbih fatimah setelah shalat yang menghapuskan dosa.',
      dalil: 'HR. Muslim no. 597.',
    },
    {
      id: 'bp-05',
      order: 5,
      title: 'Tahmid (Alhamdulillah)',
      count: 33,
      arabic: 'الْحَمْدُ لِلَّهِ',
      latin: 'Alhamdulillaah',
      translation: 'Segala puji bagi Allah.',
      fadhilah: 'Memenuhi timbangan amal kebaikan pada hari perhitungan.',
      dalil: 'HR. Muslim no. 597.',
    },
    {
      id: 'bp-06',
      order: 6,
      title: 'Takbir (Allahu Akbar)',
      count: 33,
      arabic: 'اللَّهُ أَكْبَرُ',
      latin: 'Allaahu Akbar',
      translation: 'Allah Maha Besar.',
      fadhilah: 'Mengagungkan kekuasaan Allah setelah menunaikan shalat.',
      dalil: 'HR. Muslim no. 597.',
    },
    {
      id: 'bp-07',
      order: 7,
      title: 'Penggenap Dzikir ke-100',
      count: 1,
      arabic: 'لاَ إِلَـهَ إِلاَّ اللَّهُ وَحْدَهُ لاَ شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ، وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ',
      latin: "Laa ilaaha illallaahu wahdahu laa syariika lah, lahul mulku wa lahul hamdu, wa huwa 'alaa kulli syai-in qadiir.",
      translation: 'Tidak ada Tuhan yang berhak disembah selain Allah semata, tidak ada sekutu bagi-Nya. Bagi-Nya kerajaan dan bagi-Nya segala puji, dan Dia Maha Kuasa atas segala sesuatu.',
      fadhilah: 'Rasulullah ﷺ bersabda: "Barangsiapa bertasbih 33x, bertahmid 33x, bertakbir 33x, dan menggenapkannya yang ke-100 dengan kalimat ini, maka diampuni kesalahan-kesalahannya walaupun sebanyak buih di lautan."',
      dalil: 'HR. Muslim no. 597 dari Abu Hurairah radhiyallahu ‘anhu.',
    },
    {
      id: 'bp-08',
      order: 8,
      title: 'Membaca Ayat Kursi Setelah Shalat',
      count: 1,
      arabic: 'اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَّهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ...',
      latin: "Allaahu laa ilaaha illaa huwal hayyul qayyuum...",
      translation: 'Allah, tidak ada Tuhan melainkan Dia Yang Hidup kekal lagi terus-menerus mengurus makhluk-Nya...',
      fadhilah: 'Rasulullah ﷺ bersabda: "Barangsiapa membaca Ayat Kursi setiap selesai shalat fardhu, tidak ada yang menghalanginya masuk surga selain kematian."',
      dalil: 'HR. An-Nasa’i dalam Amalul Yaum wal Lailah no. 100 dan Ibnu Hibban, dishahihkan Ibnu Hajar.',
    },
    {
      id: 'bp-09',
      order: 9,
      title: 'Membaca Surat Al-Ikhlas',
      count: 1,
      arabic: 'بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ\nقُلْ هُوَ اللَّهُ أَحَدٌ ۞ اللَّهُ الصَّمَدُ ۞ لَمْ يَلِدْ وَلَمْ يُولَدْ ۞ وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ',
      latin: 'Bismillaahir rahmaanir rahiim. Qul huwallaahu ahad. Allaahush shamad. Lam yalid wa lam yuulad. Wa lam yakul lahuu kufuwan ahad.',
      translation: 'Dengan nama Allah Yang Maha Pengasih, Maha Penyayang. Katakanlah (Muhammad), "Dialah Allah, Yang Maha Esa. Allah tempat meminta segala sesuatu. (Allah) tidak beranak dan tidak pula diperanakkan. Dan tidak ada sesuatu pun yang setara dengan Dia."',
      fadhilah: 'Dibaca 1x setelah shalat Dzuhur, Ashar, dan Isya; serta 3x setelah shalat Subuh dan Maghrib.',
      dalil: 'HR. Abu Dawud no. 1523 dan An-Nasa’i no. 1336, dinilai Shahih.',
    },
    {
      id: 'bp-10',
      order: 10,
      title: 'Membaca Surat Al-Falaq',
      count: 1,
      arabic: 'بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ\nقُلْ أَعُوذُ بِرَبِّ الْفَلَقِ ۞ مِن شَرِّ مَا خَلَقَ ۞ وَمِن شَرِّ غَاسِقٍ إِذَا وَقَبَ ۞ وَمِن شَرِّ النَّفَّاثَاتِ فِي الْعُقَدِ ۞ وَمِن شَرِّ حَاسِدٍ إِذَا حَسَدَ',
      latin: "Bismillaahir rahmaanir rahiim. Qul a'uudzu birabbil falaq. Min syarri maa khalaq. Wa min syarri ghaasiqin idzaa waqab. Wa min syarrin naffaatsaati fil 'uqad. Wa min syarri haasidin idzaa hasad.",
      translation: 'Dengan nama Allah Yang Maha Pengasih, Maha Penyayang. Katakanlah, "Aku berlindung kepada Tuhan yang menguasai subuh (fajar), dari kejahatan makhluk yang Dia ciptakan, dan dari kejahatan malam apabila telah gelap gulita, dan dari kejahatan (perempuan-perempuan) penyihir yang meniup pada buhul-buhul (talinya), dan dari kejahatan orang yang dengki apabila dia dengki."',
      fadhilah: 'Perlindungan dari segala marabahaya setelah menunaikan shalat fardhu.',
      dalil: 'HR. Abu Dawud no. 1523 dan An-Nasa’i no. 1336.',
    },
    {
      id: 'bp-11',
      order: 11,
      title: 'Membaca Surat An-Nas',
      count: 1,
      arabic: 'بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ\nقُلْ أَعُوذُ بِرَبِّ النَّاسِ ۞ مَلِكِ النَّاسِ ۞ إِلَٰهِ النَّاسِ ۞ مِن شَرِّ الْوَسْوَاسِ الْخَنَّاسِ ۞ الَّذِي يُوَسْوِسُ فِي صُدُورِ النَّاسِ ۞ مِنَ الْجِنَّةِ وَالنَّاسِ',
      latin: "Bismillaahir rahmaanir rahiim. Qul a'uudzu birabbin naas. Malikin naas. Ilaahin naas. Min syarril waswaasil khannaas. Alladzii yuwaswisu fii shuduurin naas. Minal jinnati wan naas.",
      translation: 'Dengan nama Allah Yang Maha Pengasih, Maha Penyayang. Katakanlah, "Aku berlindung kepada Tuhannya manusia, Raja manusia, Sembahan manusia, dari kejahatan (bisikan) setan yang bersembunyi, yang membisikkan (kejahatan) ke dalam dada manusia, dari (golongan) jin dan manusia."',
      fadhilah: 'Menutup shalat dengan memohon perlindungan dari bisikan setan.',
      dalil: 'HR. Abu Dawud no. 1523 dan An-Nasa’i no. 1336.',
    },
    {
      id: 'bp-12',
      order: 12,
      title: 'Doa Wasiat Rasulullah ﷺ kepada Mu’adz',
      count: 1,
      arabic: 'اللَّهُمَّ أَعِنِّي عَلَى ذِكْرِكَ وَشُكْرِكَ وَحُسْنِ عِبَادَتِكَ',
      latin: "Allahumma a'innii 'alaa dzikrika wa syukrika wa husni 'ibaadatik.",
      translation: 'Ya Allah, tolonglah aku untuk senantiasa mengingat-Mu, bersyukur kepada-Mu, dan beribadah dengan sebaik-baiknya kepada-Mu.',
      fadhilah: 'Nabi ﷺ memegang tangan Mu’adz lalu bersabda: "Demi Allah aku mencintaimu wahai Mu’adz, maka jangan tinggalkan membaca doa ini di akhir setiap shalat."',
      dalil: 'HR. Abu Dawud no. 1522 dan An-Nasa’i no. 1303, Shahih.',
    },
  ],
};

// 4. DZIKIR SEBELUM TIDUR SESUAI SUNNAH
export const sleepDhikrModule: IslamicModule = {
  id: 'sebelum-tidur',
  title: 'Sebelum Tidur',
  subtitle: 'Adab & Dzikir Malam',
  badge: 'SESUAI SUNNAH',
  timeGuide: 'Dibaca di tempat tidur menjelang beristirahat malam, diawali dengan membersihkan tempat tidur dan berwudhu.',
  items: [
    {
      id: 'st-01',
      order: 1,
      title: 'Adab Mengibaskan Tempat Tidur',
      count: 3,
      arabic: 'بِسْمِ اللَّهِ (يَنْفُضُ فِرَاشَهُ ثَلاَثَ مَرَّاتٍ)',
      latin: 'Bismillaah (Mengibaskan kasur bagian dalam dengan ujung kain sebanyak 3 kali)',
      translation: 'Dengan menyebut nama Allah.',
      fadhilah: 'Rasulullah ﷺ bersabda: "Apabila salah seorang di antara kalian menuju tempat tidurnya, hendaklah ia mengibaskan kasurnya dengan ujung sarungnya sebanyak tiga kali, karena ia tidak tahu apa yang terjadi di tempat tidurnya."',
      dalil: 'HR. Bukhari no. 6320 dan Muslim no. 2714.',
    },
    {
      id: 'st-02',
      order: 2,
      title: 'Meniup Telapak Tangan & Membaca 3 Qul',
      count: 3,
      arabic: 'قُلْ هُوَ اللَّهُ أَحَدٌ ۞ قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ ۞ قُلْ أَعُوذُ بِرَبِّ النَّاسِ',
      latin: "Mengatupkan kedua telapak tangan, meniupnya sedikit seraya membaca Al-Ikhlas, Al-Falaq, An-Nas, lalu mengusapkannya ke seluruh tubuh mulai kepala, wajah, dan tubuh depan.",
      translation: 'Membaca surat Al-Ikhlas, Al-Falaq, dan An-Nas sebanyak tiga kali putaran.',
      fadhilah: 'Aisyah radhiyallahu ‘anha meriwayatkan bahwa Nabi ﷺ senantiasa mengamalkannya setiap malam sebelum tidur sebagai perlindungan tubuh menyeluruh.',
      dalil: 'HR. Bukhari no. 5017 dan Muslim no. 2192.',
    },
    {
      id: 'st-03',
      order: 3,
      title: 'Membaca Ayat Kursi Penjaga Tidur',
      count: 1,
      arabic: 'اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ...',
      latin: "Allaahu laa ilaaha illaa huwal hayyul qayyuum...",
      translation: 'Allah, tidak ada Tuhan selain Dia Yang Maha Hidup kekal lagi terus-menerus mengurus makhluk-Nya...',
      fadhilah: 'Rasulullah ﷺ bersabda kepada Abu Hurairah: "Jika engkau membacanya sebelum tidur, senantiasa ada penjaga dari Allah yang menjagamu dan setan tidak akan mendekatimu sampai pagi."',
      dalil: 'HR. Bukhari no. 2311.',
    },
    {
      id: 'st-04',
      order: 4,
      title: 'Dua Ayat Terakhir Surat Al-Baqarah',
      count: 1,
      arabic: 'آمَنَ الرَّسُولُ بِمَا أُنزِلَ إِلَيْهِ مِن رَّبِّهِ وَالْمُؤْمِنُونَ ۚ كُلٌّ آمَنَ بِاللَّهِ وَمَلَائِكَتِهِ وَكُتُبِهِ وَرُسُلِهِ لَا نُفَرِّقُ بَيْنَ أَحَدٍ مِّن رُّسُلِهِ ۚ وَقَالُوا سَمِعْنَا وَأَطَعْنَا ۖ غُفْرَانَكَ رَبَّنَا وَإِلَيْكَ الْمَصِيرُ ۞ لَا يُكَلِّفُ اللَّهُ نَفْسًا إِلَّا وُسْعَهَا ۚ لَهَا مَا كَسَبَتْ وَعَلَيْهَا مَا اكْتَسَبَتْ ۗ رَبَّنَا لَا تُؤَاخِذْنَا إِن نَّسِينَا أَوْ أَخْطَأْنَا ۚ رَبَّنَا وَلَا تَحْمِلْ عَلَيْنَا إِصْرًا كَمَا حَمَلْتَهُ عَلَى الَّذِينَ مِن قَبْلِنَا ۚ رَبَّنَا وَلَا تُحَمِّلْنَا مَا لَا طَاقَةَ لَنَا بِهِ ۖ وَاعْفُ عَنَّا وَاغْفِرْ لَنَا وَارْحَمْنَا ۚ أَنتَ مَوْلَانَا فَانصُرْنَا عَلَى الْقَوْمِ الْكَافِرِينَ',
      latin: "Aamanar rasuulu bimaa unzila ilaihi mir rabbihii wal mu'minuun...",
      translation: 'Rasul (Muhammad) beriman kepada apa yang diturunkan kepadanya (Al-Qur’an) dari Tuhannya, demikian pula orang-orang yang beriman... (QS. Al-Baqarah: 285-286).',
      fadhilah: 'Rasulullah ﷺ bersabda: "Barangsiapa membaca dua ayat terakhir dari surat Al-Baqarah pada malam hari, niscaya keduanya telah mencukupinya (dari segala keburukan)."',
      dalil: 'HR. Bukhari no. 5009 dan Muslim no. 808.',
    },
    {
      id: 'st-05',
      order: 5,
      title: 'Tasbih Fatimah Sebelum Tidur',
      count: 100,
      arabic: 'سُبْحَانَ اللَّهِ (٣٣×) ، الْحَمْدُ لِلَّهِ (٣٣×) ، اللَّهُ أَكْبَرُ (٣٤×)',
      latin: 'Subhanallah (33x), Alhamdulillah (33x), Allahu Akbar (34x).',
      translation: 'Maha Suci Allah (33 kali), Segala puji bagi Allah (33 kali), Allah Maha Besar (34 kali).',
      fadhilah: 'Wasiat Rasulullah ﷺ kepada Ali dan Fatimah radhiyallahu ‘anhuma: "Amalan ini lebih baik bagi kalian berdua daripada seorang pembantu untuk meringankan kelelahan."',
      dalil: 'HR. Bukhari no. 3113 dan Muslim no. 2727.',
    },
    {
      id: 'st-06',
      order: 6,
      title: 'Doa Utama Menjelang Tidur',
      count: 1,
      arabic: 'بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا',
      latin: 'Bismikallaahumma amuutu wa ahyaa.',
      translation: 'Dengan nama-Mu ya Allah, aku mati dan aku hidup.',
      fadhilah: 'Menyerahkan jiwa raga saat tidur yang merupakan saudara kandung dari kematian.',
      dalil: 'HR. Bukhari no. 6312 dan Muslim no. 2711.',
    },
    {
      id: 'st-07',
      order: 7,
      title: 'Doa Meletakkan Lambung Kanan',
      count: 1,
      arabic: 'بِاسْمِكَ رَبِّي وَضَعْتُ جَنْبِي، وَبِكَ أَرْفَعُهُ، فَإِنْ أَمْسَكْتَ نَفْسِي فَارْحَمْهَا، وَإِنْ أَرْسَلْتَهَا فَاحْفَظْهَا بِمَا تَحْفَظُ بِهِ عِبَادَكَ الصَّالِحِينَ',
      latin: "Bismika Rabbii wadha'tu jambii, wa bika arfa'uh, fa in amsakta nafsii farhamhaa, wa in arsaltahaa fahfazh-haa bimaa tahfazhu bihii 'ibaadakas shaalihiin.",
      translation: 'Dengan nama-Mu wahai Tuhanku, aku meletakkan lambungku (berbaring), dan dengan nama-Mu pula aku mengangkatnya. Jika Engkau menahan nyawaku, maka rahmatilah ia; dan jika Engkau melepaskannya kembali, maka peliharalah ia sebagaimana Engkau memelihara hamba-hamba-Mu yang shalih.',
      fadhilah: 'Dibaca saat memiringkan tubuh ke sebelah kanan menghadap kiblat.',
      dalil: 'HR. Bukhari no. 6320 dan Muslim no. 2714.',
    },
    {
      id: 'st-08',
      order: 8,
      title: 'Doa Penutup Fitrah Sebelum Terlelap',
      count: 1,
      arabic: 'اللَّهُمَّ أَسْلَمْتُ نَفْسِي إِلَيْكَ، وَفَوَّضْتُ أَمْرِي إِلَيْكَ، وَوَجَّهْتُ وَجْهِي إِلَيْكَ، وَأَلْجَأْتُ ظَهْرِي إِلَيْكَ، رَغْبَةً وَرَهْبَةً إِلَيْكَ، لاَ مَلْجَأَ وَلاَ مَنْجَا مِنْكَ إِلاَّ إِلَيْكَ، آمَنْتُ بِكِتَابِكَ الَّذِي أَنْزَلْتَ، وَبِنَبِيِّكَ الَّذِي أَرْسَلْتَ',
      latin: "Allahumma aslamtu nafsii ilaika, wa fawwadhtu amrii ilaika, wa wajjahtu wajhii ilaika, wa alja'tu zhahrii ilaika, raghbatan wa rahbatan ilaika, laa malja-a wa laa manjaa minka illaa ilaika, aamantu bikitaabikalladzii anzalta, wa binabiyyikalladzii arsalta.",
      translation: 'Ya Allah, aku menyerahkan diriku kepada-Mu, aku serahkan urusanku kepada-Mu, aku hadapkan wajahku kepada-Mu, dan aku sandarkan punggungku kepada-Mu, dengan penuh harap dan cemas kepada-Mu. Tidak ada tempat berlindung dan menyelamatkan diri dari (murka)-Mu melainkan hanya kepada-Mu. Aku beriman kepada Kitab-Mu yang telah Engkau turunkan dan kepada Nabi-Mu yang telah Engkau utus.',
      fadhilah: 'Rasulullah ﷺ bersabda kepada Al-Bara’ bin ‘Azib: "Jika engkau meninggal pada malam harimu setelah membaca doa ini, maka engkau meninggal di atas fitrah (Islam)."',
      dalil: 'HR. Bukhari no. 247 dan Muslim no. 2710.',
    },
  ],
};

// 5. TATA CARA SHALAT SESUAI SUNNAH NABI ﷺ (Sifat Shalat Nabi)
export const prayerGuideModule: IslamicModule = {
  id: 'tata-cara-shalat',
  title: 'Tata Cara Shalat',
  subtitle: 'Sifat Shalat Nabi ﷺ',
  badge: 'PANDUAN LENGKAP SUNNAH',
  timeGuide: 'Panduan rukun, gerakan, bacaan, dan thuma’ninah shalat sesuai sunnah Nabi Muhammad ﷺ dari takbiratul ihram hingga salam.',
  items: [
    {
      id: 'sh-01',
      order: 1,
      title: '1. Niat & Menghadap Kiblat',
      count: 1,
      arabic: 'إِنَّمَا الأَعْمَالُ بِالنِّيَّاتِ',
      latin: "Berdiri tegak menghadap kiblat dengan penuh khusyuk, berniat di dalam hati untuk menunaikan shalat semata-mata karena Allah Ta'ala.",
      translation: 'Sesungguhnya sahnya amal tergantung pada niatnya.',
      fadhilah: 'Niat bertempat di dalam hati (ikhlas). Berdiri menghadap kiblat adalah syarat sah shalat bagi yang mampu berdiri.',
      dalil: 'HR. Bukhari no. 1 dan Muslim no. 1907.',
    },
    {
      id: 'sh-02',
      order: 2,
      title: '2. Takbiratul Ihram',
      count: 1,
      arabic: 'اللَّهُ أَكْبَرُ',
      latin: "Allaahu Akbar (Sambil mengangkat kedua tangan sejajar bahu atau sejajar daun telinga, telapak tangan menghadap kiblat).",
      translation: 'Allah Maha Besar.',
      fadhilah: 'Rukun shalat yang menandai dimulainya shalat dan diharamkannya seluruh perkara di luar shalat.',
      dalil: 'HR. Bukhari no. 735 dan Muslim no. 390.',
    },
    {
      id: 'sh-03',
      order: 3,
      title: '3. Bersedekap di Atas Dada',
      count: 1,
      arabic: 'وَضْعُ الْيُمْنَى عَلَى الْيُسْرَى عَلَى الصَّدْرِ',
      latin: "Meletakkan tangan kanan di atas punggung tangan kiri, pergelangan, atau lengan bawah kiri, lalu diletakkan di atas dada.",
      translation: 'Meletakkan tangan kanan di atas tangan kiri di dada.',
      fadhilah: 'Sikap tawadhu dan ketundukan seorang hamba di hadapan Rabb alam semesta saat shalat.',
      dalil: 'HR. Abu Dawud no. 759 dan Ibnu Khuzaimah no. 479 dengan sanad Shahih.',
    },
    {
      id: 'sh-04',
      order: 4,
      title: '4. Doa Iftitah',
      count: 1,
      arabic: 'اللَّهُمَّ بَاعِدْ بَيْنِي وَبَيْنَ خَطَايَايَ كَمَا بَاعَدْتَ بَيْنَ الْمَشْرِقِ وَالْمَغْرِبِ، اللَّهُمَّ نَقِّنِي مِنْ خَطَايَايَ كَمَا يُنَقَّى الثَّوْبُ الأَبْيَضُ مِنَ الدَّنَسِ، اللَّهُمَّ اغْسِلْنِي مِنْ خَطَايَايَ بِالثَّلْجِ وَالْمَاءِ وَالْبَرَدِ',
      latin: "Allahumma baa'id bainii wa baina khathaayaaya kamaa baa'adta bainal masyriqi wal maghrib. Allahumma naqqinii min khathaayaaya kamaa yunaqqats tsaubul abyadhu minad danas. Allahummaghsilnii min khathaayaaya bits tsalji wal maa-i wal barad.",
      translation: 'Ya Allah, jauhkanlah antara diriku dan kesalahan-kesalahanku sebagaimana Engkau menjauhkan antara timur dan barat. Ya Allah, bersihkanlah aku dari kesalahan-kesalahanku sebagaimana baju putih dibersihkan dari kotoran. Ya Allah, cucilah kesalahan-kesalahanku dengan salju, air, dan embun es.',
      fadhilah: 'Doa pembuka shalat yang selalu dibaca Rasulullah ﷺ sesudah takbir dan sebelum membaca Al-Fatihah.',
      dalil: 'HR. Bukhari no. 744 dan Muslim no. 598 dari Abu Hurairah radhiyallahu ‘anhu.',
    },
    {
      id: 'sh-05',
      order: 5,
      title: "5. Ta'awudz & Surat Al-Fatihah",
      count: 1,
      arabic: 'أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ ۞ بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ ۞ الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ ۞ الرَّحْمَٰنِ الرَّحِيمِ ۞ مَالِكِ يَوْمِ الدِّينِ ۞ إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ ۞ اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ ۞ صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ',
      latin: "A'uudzu billaahi minasy syaithaanir rajiim... Bismillaahir rahmaanir rahiim... (Diakhiri dengan ucapan: Aamiin).",
      translation: 'Membaca Ta’awudz, Basmalah, dan Surat Al-Fatihah dengan tartil, lalu mengaminkan bacaan.',
      fadhilah: 'Al-Fatihah adalah rukun shalat terbesar. Rasulullah ﷺ bersabda: "Tidak sah shalat bagi orang yang tidak membaca Fatihatul Kitab."',
      dalil: 'HR. Bukhari no. 756 dan Muslim no. 394.',
    },
    {
      id: 'sh-06',
      order: 6,
      title: '6. Membaca Surat / Ayat Al-Qur’an',
      count: 1,
      arabic: 'قِرَاءَةُ سُورَةٍ بَعْدَ الْفَاتِحَةِ فِي الرَّكْعَتَيْنِ الأُولَيَيْنِ',
      latin: 'Membaca surat atau beberapa ayat Al-Qur’an setelah Al-Fatihah pada rakaat pertama dan kedua.',
      translation: 'Membaca surat pendek atau ayat-ayat Al-Qur’an.',
      fadhilah: 'Disunnahkan membaca dengan tartil dan merenungi maknanya.',
      dalil: 'HR. Bukhari no. 776 dan Muslim no. 451.',
    },
    {
      id: 'sh-07',
      order: 7,
      title: "7. Ruku' dengan Thuma'ninah",
      count: 1,
      arabic: 'سُبْحَانَ رَبِّيَ الْعَظِيمِ (٣×)\n\nأو: سُبْحَانَكَ اللَّهُمَّ رَبَّنَا وَبِحَمْدِكَ اللَّهُمَّ اغْفِرْ لِي',
      latin: "Bertakbir seraya mengangkat tangan, lalu membungkuk ruku' dengan meluruskan punggung (sejajar), kedua tangan memegang kedua lutut seakan mencengkeramnya. Membaca:\n\nSubhaana Rabbiyal 'Azhiim (3x)",
      translation: 'Maha Suci Tuhanku Yang Maha Agung (3 kali).',
      fadhilah: 'Thuma’ninah (tenang sejenak hingga setiap ruas tulang kembali ke tempatnya) adalah rukun shalat.',
      dalil: 'HR. Muslim no. 772, Abu Dawud no. 869, dan Bukhari no. 792.',
    },
    {
      id: 'sh-08',
      order: 8,
      title: "8. I'tidal dengan Thuma'ninah",
      count: 1,
      arabic: 'سَمِعَ اللَّهُ لِمَنْ حَمِدَهُ\n\nرَبَّنَا وَلَكَ الْحَمْدُ، حَمْدًا كَثِيرًا طَيِّبًا مُبَارَكًا فِيهِ',
      latin: "Bangkit dari ruku' seraya mengangkat kedua tangan dan membaca:\nSami'allaahu liman hamidah.\nSetelah berdiri tegak membaca:\nRabbanaa wa lakal hamd, hamdan katsiiran thayyiban mubaarakan fiih.",
      translation: 'Allah Maha Mendengar siapa yang memuji-Nya. Wahai Tuhan kami, bagi-Mu segala puji, pujian yang banyak, baik, lagi penuh berkah.',
      fadhilah: 'Rasulullah ﷺ bersabda: "Aku melihat lebih dari tiga puluh malaikat berebut mencatat kalimat pujian ini pertama kali."',
      dalil: 'HR. Bukhari no. 799.',
    },
    {
      id: 'sh-09',
      order: 9,
      title: "9. Sujud Pertama dengan Thuma'ninah",
      count: 1,
      arabic: 'سُبْحَانَ رَبِّيَ الأَعْلَى (٣×)\n\nأو: سُبْحَانَكَ اللَّهُمَّ رَبَّنَا وَبِحَمْدِكَ اللَّهُمَّ اغْفِرْ لِي',
      latin: "Bertakbir tanpa mengangkat tangan, sujud bertumpu pada 7 anggota sujud: dahi & hidung, kedua telapak tangan, kedua lutut, dan ujung jari jemari kedua kaki menghadap kiblat. Membaca:\n\nSubhaana Rabbiyal A'laa (3x)",
      translation: 'Maha Suci Tuhanku Yang Maha Tinggi (3 kali).',
      fadhilah: 'Keadaan terdekat seorang hamba dengan Tuhannya adalah saat sedang bersujud, maka perbanyaklah doa.',
      dalil: 'HR. Muslim no. 482 dan Bukhari no. 812.',
    },
    {
      id: 'sh-10',
      order: 10,
      title: "10. Duduk Antara Dua Sujud (Iftirasy)",
      count: 1,
      arabic: 'رَبِّ اغْفِرْ لِي، رَبِّ اغْفِرْ لِي\n\nأو: اللَّهُمَّ اغْفِرْ لِي، وَارْحَمْنِي، وَاجْبُرْنِي، وَاهْدِنِي، وَارْزُقْنِي',
      latin: "Bangkit dari sujud bertakbir, duduk iftirasy (menghamparkan kaki kiri dan mendudukinya, menegakkan telapak kaki kanan). Membaca:\n\nRabbighfir lii, Rabbighfir lii.",
      translation: 'Wahai Tuhanku, ampunilah aku. Wahai Tuhanku, ampunilah aku.',
      fadhilah: 'Duduk dengan tenang dan thuma’ninah memohon ampunan di antara dua sujud.',
      dalil: 'HR. Abu Dawud no. 874 dan Ibnu Majah no. 897, Shahih.',
    },
    {
      id: 'sh-11',
      order: 11,
      title: '11. Sujud Kedua',
      count: 1,
      arabic: 'سُبْحَانَ رَبِّيَ الأَعْلَى (٣×)',
      latin: "Bertakbir lalu melakukan sujud kedua sama persis seperti sujud pertama dengan thuma'ninah. Membaca:\n\nSubhaana Rabbiyal A'laa (3x)",
      translation: 'Maha Suci Tuhanku Yang Maha Tinggi (3 kali).',
      fadhilah: 'Menyempurnakan satu rakaat shalat sebelum bangkit ke rakaat berikutnya.',
      dalil: 'HR. Bukhari no. 812 dan Muslim no. 482.',
    },
    {
      id: 'sh-12',
      order: 12,
      title: '12. Tasyahhud Awwal',
      count: 1,
      arabic: 'التَّحِيَّاتُ لِلَّهِ وَالصَّلَوَاتُ وَالطَّيِّبَاتُ، السَّلاَمُ عَلَيْكَ أَيُّهَا النَّبِيُّ وَرَحْمَةُ اللَّهِ وَبَرَكَاتُهُ، السَّلاَمُ عَلَيْنَا وَعَلَى عِبَادِ اللَّهِ الصَّالِحِينَ، أَشْهَدُ أَنْ لاَ إِلَـهَ إِلاَّ اللَّهُ وَأَشْهَدُ أَنَّ مُحَمَّدًا عَبْدُهُ وَرَسُولُهُ',
      latin: "Attahiyyaatu lillaahi wash shalawaatu wath thayyibaat. Assalaamu 'alaika ayyuhan nabiyyu wa rahmatullaahi wa barakaatuh. Assalaamu 'alainaa wa 'alaa 'ibaadillaahis shaalihiin. Asyhadu allaa ilaaha illallaah wa asyhadu anna Muhammadan 'abduhuu wa rasuuluh.",
      translation: 'Segala penghormatan hanya milik Allah, juga segala shalawat dan kebaikan. Keselamatan semoga tercurah kepadamu wahai Nabi, beserta rahmat Allah dan berkah-Nya. Keselamatan semoga tercurah kepada kami dan hamba-hamba Allah yang shalih. Aku bersaksi bahwa tidak ada Tuhan selain Allah, dan aku bersaksi bahwa Muhammad adalah hamba dan utusan-Nya.',
      fadhilah: 'Duduk iftirasy pada rakaat kedua (untuk shalat 3 atau 4 rakaat), mengisyaratkan jari telunjuk kanan ke arah kiblat sejak awal tasyahhud.',
      dalil: 'HR. Bukhari no. 831 dan Muslim no. 402 dari Ibnu Mas’ud radhiyallahu ‘anhu.',
    },
    {
      id: 'sh-13',
      order: 13,
      title: '13. Tasyahhud Akhir & Shalawat Ibrahimiyah',
      count: 1,
      arabic: 'التَّحِيَّاتُ لِلَّهِ... اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ، كَمَا صَلَّيْتَ عَلَى إِبْرَاهِيمَ وَعَلَى آلِ إِبْرَاهِيمَ، إِنَّكَ حَمِيدٌ مَجِيدٌ. اللَّهُمَّ بَارِكْ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ، كَمَا بَارَكْتَ عَلَى إِبْرَاهِيمَ وَعَلَى آلِ إِبْرَاهِيمَ، إِنَّكَ حَمِيدٌ مَجِيدٌ',
      latin: "Membaca Tasyahhud, dilanjutkan Shalawat Ibrahimiyah:\nAllahumma shalli 'alaa Muhammad wa 'alaa aali Muhammad, kamaa shallaita 'alaa Ibraahiim wa 'alaa aali Ibraahiim, innaka hamiidum majiid. Allahumma baarik 'alaa Muhammad wa 'alaa aali Muhammad, kamaa baarakta 'alaa Ibraahiim wa 'alaa aali Ibraahiim, innaka hamiidum majiid.",
      translation: 'Ya Allah, berilah shalawat kepada Muhammad dan keluarga Muhammad, sebagaimana Engkau telah bershalawat kepada Ibrahim dan keluarga Ibrahim, sesungguhnya Engkau Maha Terpuji lagi Maha Mulia. Ya Allah, berkatilah Muhammad dan keluarga Muhammad...',
      fadhilah: 'Duduk tawarruk (pantat duduk di lantai, kaki kiri dimasukkan di bawah betis kanan, dan kaki kanan ditegakkan) pada tasyahhud akhir.',
      dalil: 'HR. Bukhari no. 3370 dan Muslim no. 405.',
    },
    {
      id: 'sh-14',
      order: 14,
      title: '14. Doa Perlindungan dari 4 Perkara',
      count: 1,
      arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ عَذَابِ جَهَنَّمَ، وَمِنْ عَذَابِ الْقَبْرِ، وَمِنْ فِتْنَةِ الْمَحْيَا وَالْمَمَاتِ، وَمِنْ شَرِّ فِتْنَةِ الْمَسِيحِ الدَّجَّالِ',
      latin: "Allahumma innii a'uudzu bika min 'adzaabi jahannam, wa min 'adzaabil qabr, wa min fitnatil mahyaa wal mamaat, wa min syarri fitnatil masiihid dajjaal.",
      translation: 'Ya Allah, sesungguhnya aku berlindung kepada-Mu dari siksa neraka Jahannam, dari siksa kubur, dari fitnah kehidupan dan kematian, dan dari keburukan fitnah Al-Masih Ad-Dajjal.',
      fadhilah: 'Rasulullah ﷺ sangat menekankan membaca doa ini di penghujung tasyahhud akhir sebelum mengucap salam.',
      dalil: 'HR. Muslim no. 588 dari Abu Hurairah radhiyallahu ‘anhu.',
    },
    {
      id: 'sh-15',
      order: 15,
      title: '15. Mengucap Salam',
      count: 2,
      arabic: 'السَّلاَمُ عَلَيْكُمْ وَرَحْمَةُ اللَّهِ (يَمِينًا وَشِمَالاً)',
      latin: "Menoleh ke kanan hingga pipi kanan terlihat dari belakang seraya mengucapkan:\nAssalaamu 'alaikum wa rahmatullaah.\nLalu menoleh ke kiri seraya mengucapkan:\nAssalaamu 'alaikum wa rahmatullaah.",
      translation: 'Semoga keselamatan dan rahmat Allah tercurah kepada kalian.',
      fadhilah: 'Rukun penutup shalat yang menghalalkan kembali perkara-perkara yang diharamkan saat shalat.',
      dalil: 'HR. Muslim no. 582 dan Abu Dawud no. 996.',
    },
  ],
};

export const allIslamicModules: Record<string, IslamicModule> = {
  'dzikir-pagi': morningDhikrModule,
  'dzikir-petang': eveningDhikrModule,
  'bada-sholat': afterPrayerDhikrModule,
  'sebelum-tidur': sleepDhikrModule,
  'tata-cara-shalat': prayerGuideModule,
};
