'use client';
import Image from 'next/image';
import Link from 'next/link';
import { FormEvent, useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { API_URL, apiFetch } from '../lib/api';

async function publicPost<T>(path:string,body:unknown){
  const response=await fetch(`${API_URL}${path}`,{method:'POST',credentials:'include',headers:{'content-type':'application/json'},body:JSON.stringify(body)});
  const payload=await response.json().catch(()=>({}));
  if(!response.ok){
    const fieldMsgs = Array.isArray(payload.fields) ? payload.fields.flatMap((f: any) => f.messages).filter(Boolean) : [];
    const msg = fieldMsgs.length > 0 ? fieldMsgs.join('. ') : (payload.message ?? 'Permintaan belum berhasil.');
    throw new Error(msg);
  }
  return payload as T;
}
function Shell({eyebrow,title,text,children}:{eyebrow:string;title:string;text:string;children:React.ReactNode}){return <main className="flow-page"><div className="auth-stars"/><section><Link href="/"><Image src="/images/ctj-logo.webp" width={1254} height={1254} alt="Connected to Jannah"/></Link><span>{eyebrow}</span><h1>{title}</h1><p>{text}</p>{children}</section></main>}

export function VerifyEmailFlow(){const router=useRouter(),[token,setToken]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);useEffect(()=>setToken(new URLSearchParams(location.search).get('token')??sessionStorage.getItem('ctj_dev_verification')??''),[]);const verify=async()=>{setBusy(true);try{await publicPost('/auth/verify-email',{token});sessionStorage.removeItem('ctj_dev_verification');setMessage('Email berhasil diverifikasi.');setTimeout(()=>router.push('/onboarding'),600)}catch(e){setMessage(e instanceof Error?e.message:'Belum berhasil.')}finally{setBusy(false)}};const resend=async()=>{try{const result=await apiFetch<{devVerificationToken?:string}>('/auth/resend-verification',{method:'POST'});if(result.devVerificationToken)setToken(result.devVerificationToken);setMessage('Tautan verifikasi baru telah disiapkan.')}catch(e){setMessage(e instanceof Error?e.message:'Belum berhasil mengirim ulang.')}};return <Shell eyebrow="VERIFIKASI EMAIL" title="Pastikan ini benar-benar kamu." text="Kami mengirim tautan verifikasi ke emailmu. Tautan berlaku selama 24 jam.">{token&&<button className="flow-primary" disabled={busy} onClick={verify}>{busy?'Memverifikasi…':'Verifikasi email sekarang'} <b>→</b></button>}<button className="flow-secondary" onClick={resend}>Kirim ulang email</button>{message&&<p className="flow-message" role="status">{message}</p>}<Link className="flow-link" href="/login">Kembali ke login</Link></Shell>}
export function ForgotPasswordFlow(){const[message,setMessage]=useState(''),[token,setToken]=useState('');const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const email=String(new FormData(e.currentTarget).get('email'));try{const result=await publicPost<{devResetToken?:string}>('/auth/forgot-password',{email});setMessage('Jika email terdaftar, tautan pemulihan telah dikirim.');if(result.devResetToken)setToken(result.devResetToken)}catch(err){setMessage(err instanceof Error?err.message:'Belum berhasil.')}};return <Shell eyebrow="PEMULIHAN AKUN" title="Atur ulang kata sandimu." text="Masukkan email. Kami tidak akan mengungkap apakah suatu alamat terdaftar."><form onSubmit={submit}><label>Alamat email<input required type="email" name="email" autoComplete="email"/></label><button className="flow-primary">Kirim tautan <b>→</b></button></form>{message&&<p className="flow-message">{message}</p>}{token&&<Link className="flow-secondary" href={`/reset-password?token=${encodeURIComponent(token)}`}>Buka pemulihan lokal</Link>}<Link className="flow-link" href="/login">Kembali ke login</Link></Shell>}
export function ResetPasswordFlow(){const router=useRouter(),[token,setToken]=useState(''),[message,setMessage]=useState('');useEffect(()=>setToken(new URLSearchParams(location.search).get('token')??''),[]);const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const password=String(new FormData(e.currentTarget).get('password'));try{await publicPost('/auth/reset-password',{token,password});setMessage('Kata sandi diperbarui. Silakan masuk kembali.');setTimeout(()=>router.push('/login'),700)}catch(err){setMessage(err instanceof Error?err.message:'Belum berhasil.')}};return <Shell eyebrow="KATA SANDI BARU" title="Buat kunci perjalanan yang baru." text="Gunakan minimal 8 karakter dengan huruf, angka, dan simbol."><form onSubmit={submit}><label>Kata sandi baru<input required minLength={8} type="password" name="password" autoComplete="new-password"/></label><button className="flow-primary">Simpan kata sandi <b>→</b></button></form>{message&&<p className="flow-message">{message}</p>}</Shell>}
