'use client';
import Image from 'next/image';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useEffect,useState } from 'react';
import { apiFetch,ApiError } from '../lib/api';

type Preview={circleName:string;circleType:string;expiresAt:string};
export function InviteFlow({token}:{token:string}){const router=useRouter(),[preview,setPreview]=useState<Preview|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[joined,setJoined]=useState(false);useEffect(()=>{apiFetch<Preview>(`/invites/${token}`).then(setPreview).catch(cause=>setError(cause instanceof Error?cause.message:'Undangan tidak dapat dibuka.'))},[token]);const accept=async()=>{setBusy(true);try{await apiFetch(`/invites/${token}/accept`,{method:'POST'});setJoined(true)}catch(cause){if(cause instanceof ApiError&&cause.status===401){sessionStorage.setItem('ctj_after_login',`/invite/${token}`);router.push('/login');return}setError(cause instanceof Error?cause.message:'Belum berhasil bergabung.')}finally{setBusy(false)}};return <main className="invite-flow-page"><div className="invite-flow-stars"/><section><Image src="/images/ctj-logo.webp" width={1254} height={1254} alt="Connected to Jannah"/><span>{joined?'SELAMAT DATANG':'UNDANGAN CIRCLE'}</span>{error?<><h1>Undangan belum dapat dibuka</h1><p>{error}</p><Link href="/app">Kembali ke aplikasi</Link></>:!preview?<><h1>Menyiapkan undangan…</h1><p>Tunggu sejenak, kami sedang memeriksa tautan dengan aman.</p></>:joined?<><h1>Kamu telah bergabung dengan {preview.circleName}</h1><p>Privasi amalanmu tetap mengikuti pengaturan akunmu.</p><Link href="/app">Buka Circle →</Link></>:<><h1>{preview.circleName}</h1><p>Kamu diundang ke Circle {preview.circleType}. Detail amalan tidak akan terlihat tanpa izinmu.</p><small>Berlaku sampai {new Date(preview.expiresAt).toLocaleString('id-ID')}</small><button disabled={busy} onClick={accept}>{busy?'Memproses…':'Terima undangan'} <b>→</b></button></>}</section></main>}
