import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { randomBytes } from 'node:crypto';
import { DatabaseService } from './database.service';
import { DailyEntry, DailyState, EntryKind, Period, summarize } from './domain';

type Template = { key:string; title:string; note:string; period:Period; kind:EntryKind; target?:number; unit?:string; category:string; sourceLabel:string; sourceUrl:string; instructions:string };
type CircleOrigin={id:string;name:string;type:string};
type DbEntry={id:string;entry_key:string;amalan_id?:string;title:string;note:string;period:Period;kind:EntryKind;current_value:number;target_value:number;unit?:string;completed:boolean;status:'PENDING'|'COMPLETED'|'SKIPPED';source_label:string;source_url:string;instructions?:string;bookmarked?:boolean;is_personal:boolean};

export const amalanCatalog:Template[]=[
 {key:'subuh',title:'Shalat Subuh',note:'Tunaikan shalat wajib',period:'PAGI',kind:'CHECKLIST',category:'Wajib / Utama',sourceLabel:"QS. An-Nisa' 4:103",sourceUrl:'https://quran.com/4/103',instructions:'Tunaikan sesuai waktu dan tata cara shalat yang kamu pelajari dari sumber tepercaya.'},
 {key:'dzuhur',title:'Shalat Dzuhur',note:'Tunaikan shalat wajib',period:'SIANG',kind:'CHECKLIST',category:'Wajib / Utama',sourceLabel:"QS. An-Nisa' 4:103",sourceUrl:'https://quran.com/4/103',instructions:'Tunaikan sesuai waktu dan tata cara shalat yang kamu pelajari dari sumber tepercaya.'},
 {key:'ashar',title:'Shalat Ashar',note:'Tunaikan shalat wajib',period:'SORE',kind:'CHECKLIST',category:'Wajib / Utama',sourceLabel:"QS. An-Nisa' 4:103",sourceUrl:'https://quran.com/4/103',instructions:'Tunaikan sesuai waktu dan tata cara shalat yang kamu pelajari dari sumber tepercaya.'},
 {key:'maghrib',title:'Shalat Maghrib',note:'Tunaikan shalat wajib',period:'SORE',kind:'CHECKLIST',category:'Wajib / Utama',sourceLabel:"QS. An-Nisa' 4:103",sourceUrl:'https://quran.com/4/103',instructions:'Tunaikan sesuai waktu dan tata cara shalat yang kamu pelajari dari sumber tepercaya.'},
 {key:'isya',title:'Shalat Isya',note:'Tunaikan shalat wajib',period:'MALAM',kind:'CHECKLIST',category:'Wajib / Utama',sourceLabel:"QS. An-Nisa' 4:103",sourceUrl:'https://quran.com/4/103',instructions:'Tunaikan sesuai waktu dan tata cara shalat yang kamu pelajari dari sumber tepercaya.'},
 {key:'dzikir-pagi',title:'Dzikir pagi',note:'Pilih bacaan sahih yang mampu dijaga',period:'PAGI',kind:'CHECKLIST',category:'Dzikir',sourceLabel:'Sahih al-Bukhari 6306',sourceUrl:'https://sunnah.com/bukhari:6306',instructions:'Baca dzikir pagi dari himpunan yang telah diperiksa dan sumber penjelasan tepercaya.'},
 {key:'rawatib-subuh',title:'Sunnah qabliyah Subuh',note:'Dua rakaat sebelum Subuh',period:'PAGI',kind:'CHECKLIST',category:'Shalat Sunnah',sourceLabel:'Sahih Muslim 728a',sourceUrl:'https://sunnah.com/muslim:728a',instructions:'Dua rakaat sunnah sebelum shalat Subuh.'},
 {key:'dhuha',title:'Shalat Dhuha',note:'Mulai dengan dua rakaat',period:'PAGI',kind:'CHECKLIST',category:'Shalat Sunnah',sourceLabel:'Sahih Muslim 720',sourceUrl:'https://sunnah.com/muslim:720',instructions:'Mulai dengan dua rakaat pada waktu Dhuha sesuai tuntunan yang kamu ikuti.'},
 {key:'quran',title:"Membaca Al-Qur'an",note:'Tetapkan porsi yang mampu dijaga',period:'PAGI',kind:'QUANTITY',target:1,unit:'halaman',category:"Al-Qur'an",sourceLabel:'QS. Al-Muzzammil 73:20',sourceUrl:'https://quran.com/73/20',instructions:'Baca bagian yang mudah dan mampu kamu jaga secara rutin.'},
 {key:'istighfar',title:'Istighfar',note:'Memohon ampun dan kembali kepada Allah',period:'PAGI',kind:'COUNTER',target:100,unit:'kali',category:'Dzikir',sourceLabel:'Sahih al-Bukhari 6307',sourceUrl:'https://sunnah.com/bukhari:6307',instructions:'Beristighfar dengan sadar dan rendah hati. Target dapat kamu sesuaikan.'},
 {key:'tasbih',title:'Subhanallahi wa bihamdihi',note:'Dzikir yang ringan untuk dijaga',period:'PAGI',kind:'COUNTER',target:100,unit:'kali',category:'Dzikir',sourceLabel:'Sahih al-Bukhari 6405',sourceUrl:'https://sunnah.com/bukhari:6405',instructions:'Baca dengan tenang. Target dapat kamu sesuaikan dengan kemampuan.'},
 {key:'shalawat',title:'Bershalawat',note:'Memohonkan shalawat untuk Nabi ﷺ',period:'SORE',kind:'COUNTER',target:10,unit:'kali',category:'Dzikir',sourceLabel:'Sahih Muslim 408',sourceUrl:'https://sunnah.com/muslim:408',instructions:'Bershalawat kepada Nabi ﷺ dengan lafaz yang sahih.'},
 {key:'dzikir-petang',title:'Dzikir petang',note:'Luangkan waktu sebelum malam',period:'SORE',kind:'CHECKLIST',category:'Dzikir',sourceLabel:'Sahih al-Bukhari 6306',sourceUrl:'https://sunnah.com/bukhari:6306',instructions:'Baca dzikir petang dari himpunan yang telah diperiksa.'},
 {key:'kebaikan',title:'Satu kebaikan untuk sesama',note:'Senyum, membantu, atau berkata baik',period:'SIANG',kind:'CUSTOM',category:'Kebaikan Sosial',sourceLabel:"Jami' at-Tirmidhi 1956",sourceUrl:'https://sunnah.com/tirmidhi:1956',instructions:'Pilih satu bentuk kebaikan yang aman dan bermanfaat bagi orang lain.'},
 {key:'witr',title:'Shalat Witr',note:'Jadikan penutup shalat malam',period:'MALAM',kind:'CHECKLIST',category:'Shalat Sunnah',sourceLabel:'Sunan Abi Dawud 1438',sourceUrl:'https://sunnah.com/abudawud:1438',instructions:'Kerjakan shalat Witr sebagai penutup shalat malam sesuai kemampuan.'},
 {key:'sedekah',title:'Sedekah',note:'Berbagi sesuai kemampuan',period:'SIANG',kind:'CHECKLIST',category:'Sedekah',sourceLabel:'QS. Al-Baqarah 2:261',sourceUrl:'https://quran.com/2/261',instructions:'Berikan sedekah secara aman, ikhlas, dan sesuai kemampuan.'},
 {key:'belajar',title:'Belajar ilmu bermanfaat',note:'Luangkan waktu untuk belajar',period:'SIANG',kind:'DURATION',target:10,unit:'menit',category:'Ilmu',sourceLabel:'Sahih Muslim 2699',sourceUrl:'https://sunnah.com/muslim:2699',instructions:'Pelajari ilmu agama atau ilmu bermanfaat dari pengajar dan sumber tepercaya.'},
 {key:'tahajjud',title:'Shalat Tahajjud',note:'Shalat sunnah di sepertiga malam terakhir',period:'MALAM',kind:'CHECKLIST',category:'Shalat Sunnah',sourceLabel:'Sahih Muslim 1163',sourceUrl:'https://sunnah.com/muslim:1163',instructions:'Laksanakan minimal dua rakaat pada sepertiga malam terakhir setelah bangun tidur.'},
 {key:'rawatib-dzuhur',title:"Sunnah ba'diyah Dzuhur",note:'Dua rakaat sesudah shalat Dzuhur',period:'SIANG',kind:'CHECKLIST',category:'Shalat Sunnah',sourceLabel:'Sahih Muslim 728a',sourceUrl:'https://sunnah.com/muslim:728a',instructions:'Dua rakaat sunnah rawatib sesudah shalat Dzuhur.'},
 {key:'rawatib-maghrib',title:"Sunnah ba'diyah Maghrib",note:'Dua rakaat sesudah shalat Maghrib',period:'SORE',kind:'CHECKLIST',category:'Shalat Sunnah',sourceLabel:'Sahih Muslim 728a',sourceUrl:'https://sunnah.com/muslim:728a',instructions:'Dua rakaat sunnah rawatib sesudah shalat Maghrib.'},
 {key:'rawatib-isya',title:"Sunnah ba'diyah Isya",note:'Dua rakaat sesudah shalat Isya',period:'MALAM',kind:'CHECKLIST',category:'Shalat Sunnah',sourceLabel:'Sahih Muslim 728a',sourceUrl:'https://sunnah.com/muslim:728a',instructions:'Dua rakaat sunnah rawatib sesudah shalat Isya.'},
 {key:'dzikir-shalat',title:'Dzikir setelah shalat fardhu',note:'Istighfar, Ayat Kursi, dan tasbih-tahmid-takbir 33x',period:'SIANG',kind:'CHECKLIST',category:'Dzikir',sourceLabel:'Sahih Muslim 597a',sourceUrl:'https://sunnah.com/muslim:597a',instructions:"Membaca istighfar, dzikir ma'tsur, Ayat Kursi, serta tasbih, tahmid, dan takbir 33 kali seusai shalat fardhu."},
 {key:'al-mulk',title:'Membaca Surat Al-Mulk',note:'Pelindung dan pemberi syafaat sebelum tidur',period:'MALAM',kind:'CHECKLIST',category:"Al-Qur'an",sourceLabel:"Jami' at-Tirmidhi 2891",sourceUrl:'https://sunnah.com/tirmidhi:2891',instructions:'Membaca Surat Al-Mulk (30 ayat) pada malam hari sebelum tidur.'},
 {key:'doa-tidur',title:'Dzikir & doa sebelum tidur',note:'Ayat Kursi, 3 Qul, dan doa tidur',period:'MALAM',kind:'CHECKLIST',category:'Dzikir',sourceLabel:'Sahih al-Bukhari 6320',sourceUrl:'https://sunnah.com/bukhari:6320',instructions:'Membaca Ayat Kursi, Surat Al-Ikhlas, Al-Falaq, An-Nas, serta doa Bismika Allahumma amutu wa ahya.'},
 {key:'tahlil',title:'Tahlil 100x',note:'Laa ilaha illallah wahdahu laa syarika lah...',period:'PAGI',kind:'COUNTER',target:100,unit:'kali',category:'Dzikir',sourceLabel:'Sahih al-Bukhari 3293',sourceUrl:'https://sunnah.com/bukhari:3293',instructions:'Membaca lafaz tauhid lengkap 100 kali sebagai benteng perlindungan dan pelebur dosa.'},
 {key:'doa-ortu',title:'Mendoakan orang tua',note:'Rabbighfir li wa liwalidayya warhamhuma',period:'PAGI',kind:'CHECKLIST',category:'Doa',sourceLabel:"QS. Al-Isra' 17:24",sourceUrl:'https://quran.com/17/24',instructions:'Mendoakan ampunan, rahmat, dan keberkahan untuk kedua orang tua setiap hari.'},
 {key:'puasa-sunnah',title:'Puasa sunnah',note:'Senin-Kamis atau Ayyamul Bidh (13-15)',period:'PAGI',kind:'CHECKLIST',category:'Puasa',sourceLabel:"Jami' at-Tirmidhi 745",sourceUrl:'https://sunnah.com/tirmidhi:745',instructions:'Niatkan puasa sunnah di hari Senin, Kamis, atau tiga hari tengah bulan hijriyah.'},
 {key:'silaturahmi',title:'Menyapa & menjalin silaturahmi',note:'Tanyakan kabar orang tua, keluarga, atau kerabat',period:'SIANG',kind:'CHECKLIST',category:'Kebaikan Sosial',sourceLabel:'Sahih al-Bukhari 5985',sourceUrl:'https://sunnah.com/bukhari:5985',instructions:'Hubungi atau temui keluarga dan kerabat untuk mempererat tali persaudaraan.'},
 {key:'menjaga-wudhu',title:'Menjaga keadaan suci (wudhu)',note:'Memperbarui wudhu saat berhadats',period:'PAGI',kind:'CHECKLIST',category:'Thaharah',sourceLabel:'Musnad Ahmad 22433',sourceUrl:'https://sunnah.com/ahmad:22433',instructions:'Membiasakan diri senantiasa dalam keadaan suci dengan berwudhu kembali ketika batal.'},
];

@Injectable()
export class DailyV2Service {
 constructor(private readonly db:DatabaseService){}
 async catalog(userId:string){const [dbTemplates,userRows]=await Promise.all([this.db.query<any>('SELECT key,title,note,period,kind,category,target_value,unit,source_label,source_url,instructions FROM amalan_templates ORDER BY CASE period WHEN \'PAGI\' THEN 1 WHEN \'SIANG\' THEN 2 WHEN \'SORE\' THEN 3 ELSE 4 END, title'),this.db.query<any>('SELECT id,template_key,title,note,period,kind,target_value,unit,source_label,source_url,instructions,active FROM user_amalan WHERE user_id=$1',[userId])]);const list=dbTemplates.rows.length?dbTemplates.rows.map(r=>({key:r.key,title:r.title,note:r.note,period:r.period,kind:r.kind,category:r.category,target:r.target_value,unit:r.unit,sourceLabel:r.source_label,sourceUrl:r.source_url,instructions:r.instructions,isCustom:false})):amalanCatalog.map(t=>({...t,isCustom:false}));const byKey=new Map(userRows.rows.filter((r:any)=>r.template_key).map((row:any)=>[row.template_key,row]));const templateItems=list.map(item=>({...item,id:byKey.get(item.key)?.id,active:Boolean(byKey.get(item.key)?.active),target:byKey.get(item.key)?.target_value??item.target??1}));const customItems=userRows.rows.filter((r:any)=>!r.template_key).map((r:any)=>({key:r.id,id:r.id,title:r.title,note:r.note,category:'Amalan Pribadi',period:r.period,kind:r.kind,target:r.target_value,unit:r.unit,active:Boolean(r.active),sourceLabel:r.source_label||'Amalan pribadi',sourceUrl:r.source_url||'',instructions:r.instructions||'',isCustom:true}));return[...templateItems,...customItems]}
 async configure(userId:string,keys:string[],timezone:string,remindersEnabled:boolean,avatar='najm'){const templatesResult=await this.db.query<any>('SELECT key,title,note,period,kind,target_value,unit,source_label,source_url,instructions FROM amalan_templates');const templates=templatesResult.rows.length?templatesResult.rows:amalanCatalog.map(t=>({...t,target_value:t.target??1,source_label:t.sourceLabel,source_url:t.sourceUrl}));const selected=[...new Set(keys)].filter(key=>templates.some((item:any)=>item.key===key));if(!selected.length)throw new BadRequestException({code:'AMALAN_REQUIRED',message:'Pilih setidaknya satu amalan untuk memulai.'});await this.db.transaction(async client=>{for(const item of templates){const enabled=selected.includes(item.key);await client.query(`INSERT INTO user_amalan(id,user_id,template_key,title,note,period,kind,target_value,unit,source_label,source_url,instructions,active) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) ON CONFLICT(user_id,template_key) DO UPDATE SET active=excluded.active`,[randomBytes(10).toString('hex'),userId,item.key,item.title,item.note,item.period,item.kind,item.target_value??1,item.unit??null,item.source_label??item.sourceLabel,item.source_url??item.sourceUrl,item.instructions,enabled])}await client.query('UPDATE users SET onboarding_completed=true,timezone=$2,reminders_enabled=$3,avatar=$4 WHERE id=$1',[userId,timezone,remindersEnabled,avatar])});return{success:true}}
  async get(userId:string,date=this.localDate()):Promise<DailyState>{await this.ensureDay(userId,date);const [result,originRows,streakRows,totalRows]=await Promise.all([this.db.query<DbEntry>(`SELECT d.id,d.entry_key,u.id AS amalan_id,d.title,d.note,d.period,d.kind,d.current_value,d.target_value,d.unit,d.completed,d.status,d.source_label,d.source_url,u.instructions,(b.amalan_id IS NOT NULL) AS bookmarked,coalesce(u.active,false) AS is_personal FROM daily_entries d LEFT JOIN user_amalan u ON u.user_id=d.user_id AND (u.template_key=d.entry_key OR u.id=d.entry_key) LEFT JOIN bookmarks b ON b.user_id=d.user_id AND b.amalan_id=u.id WHERE d.user_id=$1 AND d.local_date=$2 AND (coalesce(u.active,false) OR EXISTS(SELECT 1 FROM circle_amalan ca JOIN circle_members cm ON cm.circle_id=ca.circle_id AND cm.user_id=d.user_id AND cm.status='ACTIVE' JOIN circles c ON c.id=ca.circle_id AND c.archived_at IS NULL WHERE ca.template_key=d.entry_key)) ORDER BY CASE WHEN d.status='COMPLETED' OR d.completed THEN 1 ELSE 0 END ASC, CASE d.period WHEN 'PAGI' THEN 1 WHEN 'SIANG' THEN 2 WHEN 'SORE' THEN 3 ELSE 4 END, d.title`,[userId,date]),this.db.query<{template_key:string;circles:CircleOrigin[]}>(`SELECT ca.template_key,jsonb_agg(DISTINCT jsonb_build_object('id',c.id,'name',c.name,'type',c.type)) AS circles FROM circle_amalan ca JOIN circles c ON c.id=ca.circle_id AND c.archived_at IS NULL JOIN circle_members cm ON cm.circle_id=c.id AND cm.user_id=$1 AND cm.status='ACTIVE' GROUP BY ca.template_key`,[userId]),this.db.query<{local_date:string}>('SELECT DISTINCT local_date::text FROM daily_entries WHERE user_id=$1 AND completed=true AND local_date<=$2 ORDER BY local_date DESC',[userId,date]),this.db.query<any>('SELECT count(DISTINCT local_date) FILTER(WHERE completed)::int AS active_days,count(*) FILTER(WHERE completed)::int AS total_xp FROM daily_entries WHERE user_id=$1',[userId])]);const origins=new Map(originRows.rows.map(row=>[row.template_key,row.circles??[]]));return this.toState(result.rows.map(row=>this.mapEntry(row,origins.get(row.entry_key)??[])),date,this.streak(date,streakRows.rows.map(row=>row.local_date)),Number(totalRows.rows[0]?.active_days??0),Number(totalRows.rows[0]?.total_xp??0))}
  async complete(userId:string,entryId:string,clientMutationId:string):Promise<DailyState>{await this.db.transaction(async client=>{const previous=await client.query('SELECT 1 FROM daily_mutations WHERE user_id=$1 AND client_mutation_id=$2',[userId,clientMutationId]);if(previous.rowCount)return;const result=await client.query<{entry_key:string;title:string}>('UPDATE daily_entries SET current_value=target_value,completed=true,status=\'COMPLETED\' WHERE id=$1 AND user_id=$2 AND status=\'PENDING\' RETURNING entry_key,title',[entryId,userId]);if(!result.rowCount){const exists=await client.query('SELECT 1 FROM daily_entries WHERE id=$1 AND user_id=$2',[entryId,userId]);if(!exists.rowCount)throw new NotFoundException({code:'ENTRY_NOT_FOUND',message:'Amalan tidak ditemukan.'})}else{const entryKey=result.rows[0].entry_key,entryTitle=result.rows[0].title;const challengeByEntry:Record<string,string>={dhuha:'dhuha-30',quran:'quran-30',istighfar:'istighfar-30'},challengeId=challengeByEntry[entryKey];if(challengeId){const chRes=await client.query<{status:string}>(`UPDATE challenge_memberships SET current_value=least(current_value+1,30),completed_at=CASE WHEN current_value+1>=30 THEN now() ELSE completed_at END,status=CASE WHEN current_value+1>=30 THEN 'COMPLETED' ELSE status END WHERE user_id=$1 AND challenge_id=$2 AND status='ACTIVE' RETURNING status`,[userId,challengeId]);if(chRes.rows[0]?.status==='COMPLETED'){await client.query(`INSERT INTO notifications(id,user_id,title,message) SELECT $1,$2,'Tantangan Selesai 🎉',$3 FROM users u WHERE u.id=$2 AND COALESCE((u.notification_categories->>'milestones')::boolean, true)=true`,[randomBytes(8).toString('hex'),userId,`Barakallahu fiik! Kamu telah menyelesaikan target 30 hari untuk tantangan ${entryTitle}.`]);}}const matchingCircles=await client.query<{id:string;name:string;display_name:string;privacy_visibility:string}>(`SELECT c.id,c.name,u.display_name,u.privacy_visibility FROM circles c JOIN circle_members cm ON cm.circle_id=c.id AND cm.user_id=$1 AND cm.status='ACTIVE' JOIN circle_amalan ca ON ca.circle_id=c.id AND ca.template_key=$2 JOIN users u ON u.id=$1 WHERE c.archived_at IS NULL`,[userId,entryKey]);for(const circle of matchingCircles.rows){const actorName=circle.privacy_visibility==='PRIVATE'?'Seorang anggota':circle.display_name;await client.query(`INSERT INTO circle_activity(id,circle_id,actor_id,event_type,message) VALUES($1,$2,$3,'AMALAN_COMPLETED',$4)`,[randomBytes(8).toString('hex'),circle.id,userId,`${actorName} menyelesaikan ${entryTitle}.`])}}await client.query('INSERT INTO daily_mutations(user_id,client_mutation_id) VALUES($1,$2)',[userId,clientMutationId])});return this.get(userId)}
 async skip(userId:string,entryId:string){const result=await this.db.query('UPDATE daily_entries SET status=\'SKIPPED\',completed=false WHERE id=$1 AND user_id=$2 AND status=\'PENDING\' RETURNING id',[entryId,userId]);if(!result.rowCount)throw new NotFoundException({code:'ENTRY_NOT_FOUND',message:'Amalan tidak ditemukan atau sudah diproses.'});return this.get(userId)}
 async history(userId:string,days=30){const result=await this.db.query<any>(`SELECT local_date::text AS date,count(*) FILTER(WHERE status!='SKIPPED')::int AS total,count(*) FILTER(WHERE completed)::int AS completed,json_agg(json_build_object('id',id,'title',title,'completed',completed,'status',status) ORDER BY title) AS entries FROM daily_entries WHERE user_id=$1 AND local_date>=current_date-$2::int GROUP BY local_date ORDER BY local_date DESC`,[userId,Math.min(days,180)]);return result.rows.map(row=>({...row,percentage:row.total?Math.round(row.completed/row.total*100):0}))}
 async addCustom(userId:string,input:{title:string;note:string;period:Period;kind:EntryKind;target:number;unit?:string}){const id=randomBytes(10).toString('hex');await this.db.query('INSERT INTO user_amalan(id,user_id,title,note,period,kind,target_value,unit,source_label,source_url,instructions) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)',[id,userId,input.title,input.note,input.period,input.kind,input.target,input.unit??null,'Amalan pribadi','','Catatan pribadi yang kamu buat sendiri.']);await this.ensureDay(userId,this.localDate());return{success:true,id}}
 async addTemplate(userId:string,key:string){const result=await this.db.query<any>('SELECT key,title,note,period,kind,target_value,unit,source_label,source_url,instructions FROM amalan_templates WHERE key=$1',[key]);const item=result.rows[0]??amalanCatalog.find(template=>template.key===key);if(!item)throw new NotFoundException({code:'AMALAN_TEMPLATE_NOT_FOUND',message:'Pilihan amalan tidak ditemukan.'});const id=randomBytes(10).toString('hex');await this.db.query(`INSERT INTO user_amalan(id,user_id,template_key,title,note,period,kind,target_value,unit,source_label,source_url,instructions,active) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,true) ON CONFLICT(user_id,template_key) DO UPDATE SET active=true`,[id,userId,item.key,item.title,item.note,item.period,item.kind,item.target_value??item.target??1,item.unit??null,item.source_label??item.sourceLabel,item.source_url??item.sourceUrl,item.instructions]);await this.ensureDay(userId,this.localDate());return{success:true}}
 async activateAllTemplates(userId:string){const templatesResult=await this.db.query<any>('SELECT key,title,note,period,kind,target_value,unit,source_label,source_url,instructions FROM amalan_templates');const templates=templatesResult.rows.length?templatesResult.rows:amalanCatalog.map(t=>({...t,target_value:t.target??1,source_label:t.sourceLabel,source_url:t.sourceUrl}));await this.db.transaction(async client=>{for(const item of templates){await client.query(`INSERT INTO user_amalan(id,user_id,template_key,title,note,period,kind,target_value,unit,source_label,source_url,instructions,active) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,true) ON CONFLICT(user_id,template_key) DO UPDATE SET active=true`,[randomBytes(10).toString('hex'),userId,item.key,item.title,item.note,item.period,item.kind,item.target_value??1,item.unit??null,item.source_label??item.sourceLabel,item.source_url??item.sourceUrl,item.instructions])}});await this.ensureDay(userId,this.localDate());return{success:true}}
 async setActive(userId:string,id:string,active:boolean){const result=await this.db.query<{template_key?:string}>('UPDATE user_amalan SET active=$3 WHERE id=$1 AND user_id=$2 RETURNING template_key',[id,userId,active]);if(!result.rowCount)throw new NotFoundException({code:'AMALAN_NOT_FOUND',message:'Amalan tidak ditemukan.'});if(active)await this.ensureDay(userId,this.localDate());else await this.db.query(`UPDATE daily_entries SET status='SKIPPED',completed=false WHERE user_id=$1 AND local_date=$2 AND entry_key=coalesce($3,$4) AND status='PENDING'`,[userId,this.localDate(),result.rows[0].template_key,id]);return{success:true}}
 async deleteAmalan(userId:string,id:string){const amalan=await this.db.query<any>('SELECT id,template_key,active FROM user_amalan WHERE id=$1 AND user_id=$2',[id,userId]);if(!amalan.rowCount)throw new NotFoundException({code:'AMALAN_NOT_FOUND',message:'Amalan tidak ditemukan.'});const row=amalan.rows[0];if(row.template_key){await this.setActive(userId,id,false);return{success:true,deactivated:true}}else{await this.db.transaction(async client=>{await client.query('DELETE FROM bookmarks WHERE user_id=$1 AND amalan_id=$2',[userId,id]);await client.query('DELETE FROM daily_entries WHERE user_id=$1 AND entry_key=$2',[userId,id]);await client.query('DELETE FROM user_amalan WHERE id=$1 AND user_id=$2',[id,userId]);});return{success:true,deleted:true}}}
 async setTarget(userId:string,id:string,target:number){const result=await this.db.query<{template_key?:string}>('UPDATE user_amalan SET target_value=$3 WHERE id=$1 AND user_id=$2 RETURNING template_key',[id,userId,target]);if(!result.rowCount)throw new NotFoundException({code:'AMALAN_NOT_FOUND',message:'Amalan tidak ditemukan.'});await this.db.query(`UPDATE daily_entries SET target_value=$4 WHERE user_id=$1 AND local_date=$2 AND entry_key=coalesce($3,$5) AND status='PENDING'`,[userId,this.localDate(),result.rows[0].template_key,target,id]);return{success:true}}
 async bookmark(userId:string,id:string,bookmarked:boolean){if(bookmarked)await this.db.query('INSERT INTO bookmarks(user_id,amalan_id) SELECT $1,id FROM user_amalan WHERE id=$2 AND user_id=$1 ON CONFLICT DO NOTHING',[userId,id]);else await this.db.query('DELETE FROM bookmarks WHERE user_id=$1 AND amalan_id=$2',[userId,id]);return{success:true,bookmarked}}
 private async ensureDay(userId:string,date:string){const [personal,circleFocus]=await Promise.all([this.db.query<any>('SELECT * FROM user_amalan WHERE user_id=$1 AND active=true',[userId]),this.db.query<any>(`SELECT DISTINCT ON(ca.template_key) ca.*, at.title as t_title, at.note as t_note, at.period as t_period, at.kind as t_kind, at.target_value as t_target, at.unit as t_unit, at.source_label as t_source_label, at.source_url as t_source_url FROM circle_amalan ca JOIN circles c ON c.id=ca.circle_id AND c.archived_at IS NULL JOIN circle_members cm ON cm.circle_id=c.id AND cm.user_id=$1 AND cm.status='ACTIVE' LEFT JOIN amalan_templates at ON at.key=ca.template_key ORDER BY ca.template_key,ca.position`,[userId])]);const entries=new Map<string,any>();for(const item of personal.rows)entries.set(item.template_key??item.id,item);for(const focus of circleFocus.rows){if(!entries.has(focus.template_key)){if(focus.t_title){entries.set(focus.template_key,{title:focus.t_title,note:focus.t_note,period:focus.t_period,kind:focus.t_kind,target_value:focus.t_target??1,unit:focus.t_unit,source_label:focus.t_source_label,source_url:focus.t_source_url})}else{entries.set(focus.template_key,{title:focus.title,note:focus.note??'',period:focus.period,kind:focus.kind,target_value:focus.target_value??1,unit:focus.unit,source_label:'Kesepakatan internal Circle',source_url:''})}}}for(const[key,item]of entries){const id=`${userId}-${date}-${key}`;await this.db.query('INSERT INTO daily_entries(id,user_id,local_date,entry_key,title,note,period,kind,target_value,unit,source_label,source_url) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) ON CONFLICT(user_id,local_date,entry_key) DO NOTHING',[id,userId,date,key,item.title,item.note,item.period,item.kind,item.target_value??item.target??1,item.unit??null,item.source_label??item.sourceLabel??'Amalan pribadi',item.source_url??item.sourceUrl??''])}}
 private mapEntry=(row:DbEntry,circles:CircleOrigin[]):DailyEntry=>({id:row.id,amalanId:row.amalan_id,title:row.title,note:row.note,period:row.period,kind:row.kind,current:row.current_value,target:row.target_value,unit:row.unit,completed:row.completed,status:row.status,sourceLabel:row.source_label,sourceUrl:row.source_url,instructions:row.instructions,bookmarked:Boolean(row.bookmarked),isPersonal:Boolean(row.is_personal),circles});
 private localDate(){return new Intl.DateTimeFormat('en-CA',{timeZone:process.env.APP_TIME_ZONE??'Asia/Jakarta',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
 private streak(today:string,dates:string[]){const completed=new Set(dates),cursor=new Date(`${today}T00:00:00Z`);let count=0;while(completed.has(cursor.toISOString().slice(0,10))){count++;cursor.setUTCDate(cursor.getUTCDate()-1)}return count}
 private toState(entries:DailyEntry[],date:string,consistencyDays:number,activeDays:number,totalXp:number):DailyState{const considered=entries.filter(entry=>entry.status!=='SKIPPED'),summary=summarize(considered),gardenStage=activeDays>=30?3:activeDays>=7?2:1,nextLevelXp=20,currentXp=totalXp%nextLevelXp,level=Math.floor(totalXp/nextLevelXp)+1;return{date,entries,summary,experience:{level,totalXp,currentXp,nextLevelXp,percentage:Math.round(currentXp/nextLevelXp*100)},journey:{consistencyDays,activeDays,energy:summary.percentage,gardenStage,message:summary.percentage===100?'Perjalanan hari ini selesai.':activeDays?'Perjalananmu tetap ada. Hari ini kita lanjutkan kembali.':'Setiap langkah kecil ikut menumbuhkan perjalananmu.'}}}
}
