import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { createHash, randomBytes } from 'node:crypto';
import { DatabaseService } from './database.service';
import { amalanCatalog } from './daily-v2.service';

const challengeCatalog=[
 {id:'dhuha-30',title:'30 Hari Dhuha',description:'Jaga dua rakaat Dhuha selama 30 hari.',target:30,unit:'hari',icon:'☀',sourceLabel:'Sahih Muslim 720',sourceUrl:'https://sunnah.com/muslim:720'},
 {id:'quran-30',title:"30 Hari Bersama Al-Qur'an",description:'Baca porsi yang mampu kamu jaga setiap hari.',target:30,unit:'hari',icon:'▤',sourceLabel:'QS. Al-Muzzammil 73:20',sourceUrl:'https://quran.com/73/20'},
 {id:'istighfar-30',title:'30 Hari Istighfar',description:'Luangkan waktu untuk memohon ampun setiap hari.',target:30,unit:'hari',icon:'♡',sourceLabel:'Sahih al-Bukhari 6307',sourceUrl:'https://sunnah.com/bukhari:6307'},
];
export const encouragementMessages:Record<string,string>={ease:'Semoga Allah mudahkan harimu.',continue:'Yuk, lanjutkan perjalanan hari ini.',little:'Sedikit demi sedikit, tetap berarti.',steadfast:'Semoga Allah menjaga istiqamah kita.',goodness:'Semoga hari ini penuh kebaikan.'};
type CircleCustomAmalan={title:string;note:string;period:string;kind:string;target:number;unit?:string};

@Injectable()
export class AppDataV2Service{
 constructor(private readonly db:DatabaseService){}
 async getOverview(userId:string){const [circleRows,memberships,notifications,user,activityRows,challengeRows]=await Promise.all([
  this.db.query<any>(`SELECT c.id,c.name,c.type,own.role,count(m.user_id) FILTER(WHERE m.status='ACTIVE')::int AS members FROM circles c JOIN circle_members own ON own.circle_id=c.id AND own.user_id=$1 AND own.status='ACTIVE' LEFT JOIN circle_members m ON m.circle_id=c.id WHERE c.archived_at IS NULL GROUP BY c.id,own.role ORDER BY c.created_at DESC`,[userId]),
  this.db.query<any>('SELECT challenge_id,current_value,status,missed_day_policy,joined_at,paused_at,completed_at FROM challenge_memberships WHERE user_id=$1 AND status<>\'LEFT\'',[userId]),
  this.db.query<any>('SELECT id,title,message,read,created_at FROM notifications WHERE user_id=$1 ORDER BY created_at DESC LIMIT 30',[userId]),
  this.db.query<any>('SELECT privacy_visibility,reminders_enabled,reduced_motion,quiet_start::text,quiet_end::text,notification_categories,timezone,language,location_name,latitude,longitude FROM users WHERE id=$1',[userId]),
  this.db.query<any>('SELECT count(*) FILTER (WHERE completed)::int AS completed_entries,count(DISTINCT local_date) FILTER (WHERE completed)::int AS active_days FROM daily_entries WHERE user_id=$1',[userId]),
  this.db.query<any>('SELECT id,title,description,target_value,unit,days_left,icon,source_label,source_url FROM challenges ORDER BY id'),
 ]);const challengesList=challengeRows.rows.map(r=>({id:r.id,title:r.title,description:r.description,target:Number(r.target_value),unit:r.unit,daysLeft:Number(r.days_left),icon:r.icon,sourceLabel:r.source_label,sourceUrl:r.source_url}));const joined=new Map(memberships.rows.map(x=>[x.challenge_id,x])),activity=activityRows.rows[0],completed=Number(activity?.completed_entries??0),days=Number(activity?.active_days??0),stage=days>=30?3:days>=7?2:1,u=user.rows[0]??{};return{circles:circleRows.rows.map(c=>({...c,icon:c.type==='Keluarga'?'⌂':c.type==='Kajian'?'✦':'♧',message:'Ruang perjalanan bersama'})),challenges:challengesList.map(c=>{const state=joined.get(c.id);return{...c,current:Number(state?.current_value??0),joined:Boolean(state),status:state?.status??'NOT_JOINED',missedDayPolicy:state?.missed_day_policy??'CONTINUE',joinedAt:state?.joined_at?.toISOString?.()}}),garden:{name:stage===3?'Paviliun Cahaya':stage===2?'Taman Berbunga':'Taman Perjalanan',stage,plants:Math.min(completed,12),buildings:Math.min(Math.floor(completed/7),10),decorations:Math.min(Math.floor(completed/3),15),activeDays:days,nextMilestone:days>=7?'Tiga puluh hari perjalanan':'Tujuh hari perjalanan',milestoneProgress:days>=7?Math.min(days,30):days,milestoneTarget:days>=7?30:7},notifications:notifications.rows.map(n=>({...n,createdAt:n.created_at.toISOString()})),privacy:{visibility:u.privacy_visibility??'COMPLETION_ONLY'},preferences:{remindersEnabled:u.reminders_enabled??true,reducedMotion:u.reduced_motion??false,quietStart:u.quiet_start,quietEnd:u.quiet_end,categories:u.notification_categories??{reminders:true,circles:true,milestones:true}},location:{timezone:u.timezone,language:u.language,name:u.location_name,latitude:u.latitude,longitude:u.longitude}}}
 async createCircle(userId:string,name:string,type:string,keys:string[]=['subuh'],custom:CircleCustomAmalan[]=[]){const selected=await this.validAmalan(keys),customItems=custom.slice(0,6);if(!selected.length&&!customItems.length)throw new BadRequestException({code:'CIRCLE_AMALAN_REQUIRED',message:'Pilih atau buat setidaknya satu amalan untuk Circle.'});const id=randomBytes(8).toString('hex');await this.db.transaction(async client=>{await client.query('INSERT INTO circles(id,owner_id,name,type) VALUES($1,$2,$3,$4)',[id,userId,name,type]);await client.query('INSERT INTO circle_members(circle_id,user_id,role) VALUES($1,$2,\'OWNER\')',[id,userId]);for(const [position,key] of selected.entries())await client.query('INSERT INTO circle_amalan(circle_id,template_key,selected_by,position) VALUES($1,$2,$3,$4)',[id,key,userId,position]);for(const [offset,item] of customItems.entries())await client.query('INSERT INTO circle_amalan(circle_id,template_key,selected_by,position,is_custom,title,note,period,kind,target_value,unit) VALUES($1,$2,$3,$4,true,$5,$6,$7,$8,$9,$10)',[id,`custom-${randomBytes(8).toString('hex')}`,userId,selected.length+offset,item.title.trim(),item.note.trim(),item.period,item.kind,item.target,item.unit?.trim()||null]);const total=selected.length+customItems.length;await client.query('INSERT INTO circle_activity(id,circle_id,actor_id,event_type,message) VALUES($1,$2,$3,\'CREATED\',$4)',[randomBytes(8).toString('hex'),id,userId,`Circle dibuat dengan ${total} fokus amalan.`])});return{id,name,type,members:1,role:'OWNER',amalanCount:selected.length+customItems.length}}
 async circleDetail(userId:string,circleId:string){
  await this.assertMember(userId,circleId);
  const [circle,members,activity,shared,focusRows,dailyProgressRows]=await Promise.all([
   this.db.query<any>('SELECT c.id,c.name,c.type,c.owner_id,c.test_experience,m.role FROM circles c JOIN circle_members m ON m.circle_id=c.id AND m.user_id=$1 WHERE c.id=$2',[userId,circleId]),
   this.db.query<any>(`SELECT u.id,u.display_name,u.avatar,m.role,m.status,m.joined_at FROM circle_members m JOIN users u ON u.id=m.user_id WHERE m.circle_id=$1 ORDER BY CASE m.role WHEN 'OWNER' THEN 1 WHEN 'ADMIN' THEN 2 ELSE 3 END,m.joined_at`,[circleId]),
   this.db.query<any>(`SELECT a.id,a.event_type,a.message,a.created_at,CASE WHEN u.id=$2 OR coalesce(u.privacy_visibility,'CIRCLE')<>'PRIVATE' THEN u.display_name ELSE 'Anggota privat' END AS display_name,CASE WHEN u.id=$2 OR coalesce(u.privacy_visibility,'CIRCLE')<>'PRIVATE' THEN u.avatar ELSE '' END AS avatar FROM circle_activity a LEFT JOIN users u ON u.id=a.actor_id WHERE a.circle_id=$1 ORDER BY a.created_at DESC LIMIT 50`,[circleId,userId]),
   this.db.query<any>(`SELECT count(DISTINCT d.user_id)::int AS active_members,count(DISTINCT d.local_date)::int AS active_days,count(*)::int AS contributions FROM daily_entries d JOIN circle_members m ON m.user_id=d.user_id AND m.circle_id=$1 AND m.status='ACTIVE' JOIN circle_amalan ca ON ca.circle_id=$1 AND ca.template_key=d.entry_key WHERE d.completed=true`,[circleId]),
   this.db.query<any>(`SELECT ca.template_key,ca.is_custom,coalesce(ca.title,at.title) AS title,coalesce(ca.note,at.note,'') AS note,coalesce(ca.period,at.period) AS period,coalesce(ca.kind,at.kind) AS kind,coalesce(ca.target_value,at.target_value,1) AS target_value,coalesce(ca.unit,at.unit) AS unit,coalesce(at.category,'Custom Circle') AS category,coalesce(at.source_label,'Kesepakatan internal Circle') AS source_label,coalesce(at.source_url,'') AS source_url,count(DISTINCT d.user_id) FILTER(WHERE d.completed AND d.local_date=(now() AT TIME ZONE 'Asia/Jakarta')::date)::int AS completed_members FROM circle_amalan ca LEFT JOIN amalan_templates at ON at.key=ca.template_key LEFT JOIN circle_members m ON m.circle_id=ca.circle_id AND m.status='ACTIVE' LEFT JOIN daily_entries d ON d.user_id=m.user_id AND d.entry_key=ca.template_key WHERE ca.circle_id=$1 GROUP BY ca.template_key,ca.position,ca.is_custom,ca.title,ca.note,ca.period,ca.kind,ca.target_value,ca.unit,at.title,at.note,at.period,at.kind,at.target_value,at.unit,at.category,at.source_label,at.source_url ORDER BY ca.position`,[circleId]),
   this.db.query<any>(`WITH member_progress AS (SELECT u.id,CASE WHEN u.id=$2 OR coalesce(u.privacy_visibility,'CIRCLE')<>'PRIVATE' THEN u.display_name ELSE 'Anggota privat' END AS display_name,CASE WHEN u.id=$2 OR coalesce(u.privacy_visibility,'CIRCLE')<>'PRIVATE' THEN u.avatar ELSE '' END AS avatar,m.joined_at,count(DISTINCT ca.template_key)::int AS target,count(DISTINCT d.entry_key) FILTER(WHERE d.completed)::int AS contributions FROM circle_members m JOIN users u ON u.id=m.user_id LEFT JOIN circle_amalan ca ON ca.circle_id=m.circle_id LEFT JOIN daily_entries d ON d.user_id=m.user_id AND d.entry_key=ca.template_key AND d.local_date=(now() AT TIME ZONE 'Asia/Jakarta')::date WHERE m.circle_id=$1 AND m.status='ACTIVE' GROUP BY u.id,u.display_name,u.avatar,u.privacy_visibility,m.joined_at),ranked AS (SELECT *,row_number() OVER(ORDER BY contributions DESC,joined_at ASC)::int AS rank,sum(contributions) OVER()::int AS daily_total FROM member_progress) SELECT *,(now() AT TIME ZONE 'Asia/Jakarta')::date::text AS progress_date FROM ranked ORDER BY rank LIMIT 3`,[circleId,userId])
  ]);
  if(!circle.rowCount)throw new NotFoundException({code:'CIRCLE_NOT_FOUND',message:'Circle tidak ditemukan.'});
  const activeMembers=members.rows.filter(m=>m.status==='ACTIVE').length;
  const circleAmalan=focusRows.rows.map(row=>({key:row.template_key,title:row.title,category:row.category,period:row.period,sourceLabel:row.source_label,sourceUrl:row.source_url,completedMembers:Number(row.completed_members??0),activeMembers,isCustom:Boolean(row.is_custom),note:row.note,kind:row.kind,target:Number(row.target_value),unit:row.unit}));
  const {test_experience:testingExperience,...circleData}=circle.rows[0],actualContributions=Number(shared.rows[0]?.contributions??0),contributions=process.env.NODE_ENV!=='production'&&testingExperience!==null?Number(testingExperience):actualContributions;
  const progressDate=dailyProgressRows.rows[0]?.progress_date??new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jakarta'}).format(new Date());
  return{...circleData,members:members.rows.map(m=>({...m,joinedAt:m.joined_at.toISOString()})),circleAmalan,activity:activity.rows.map(a=>({...a,createdAt:a.created_at.toISOString()})),dailyProgress:{date:progressDate,total:Number(dailyProgressRows.rows[0]?.daily_total??0),members:dailyProgressRows.rows.map(row=>{const target=Number(row.target??0),memberContributions=Number(row.contributions??0);return{id:row.id,display_name:row.display_name,avatar:row.avatar??'',contributions:memberContributions,target,progressPercent:target?Math.min(100,Math.round(memberContributions/target*100)):0,rank:Number(row.rank)}})},sharedJourney:{activeMembers:Number(shared.rows[0]?.active_members??0),activeDays:Number(shared.rows[0]?.active_days??0),contributions},testing:process.env.NODE_ENV!=='production'&&testingExperience!==null?{level:Math.floor(contributions/20)+1,experience:contributions}:undefined}
 }

 async setTestCircleLevel(userId:string,circleId:string,level:number){this.assertTestingEnabled();await this.assertRole(userId,circleId,['OWNER']);const experience=(level-1)*20;await this.db.query('UPDATE circles SET test_experience=$2 WHERE id=$1',[circleId,experience]);return{success:true,circleId,level,experience,nextLevelAt:level*20,testing:true}}
 async resetTestCircleLevel(userId:string,circleId:string){this.assertTestingEnabled();await this.assertRole(userId,circleId,['OWNER']);await this.db.query('UPDATE circles SET test_experience=NULL WHERE id=$1',[circleId]);return{success:true,circleId,testing:false}}
 async updateCircleAmalan(userId:string,circleId:string,keys:string[]){
  await this.assertRole(userId,circleId,['OWNER']);const selected=await this.validAmalan(keys),customCount=await this.db.query<any>('SELECT count(*)::int AS count FROM circle_amalan WHERE circle_id=$1 AND is_custom=true',[circleId]);
  if(!selected.length&&!Number(customCount.rows[0]?.count))throw new BadRequestException({code:'CIRCLE_AMALAN_REQUIRED',message:'Sisakan setidaknya satu amalan katalog atau custom untuk Circle.'});
  await this.db.transaction(async client=>{await client.query('DELETE FROM circle_amalan WHERE circle_id=$1 AND is_custom=false',[circleId]);await client.query(`WITH ranked AS (SELECT template_key,row_number() OVER(ORDER BY position,created_at)-1 AS next_position FROM circle_amalan WHERE circle_id=$1 AND is_custom=true) UPDATE circle_amalan ca SET position=$2+ranked.next_position FROM ranked WHERE ca.circle_id=$1 AND ca.template_key=ranked.template_key`,[circleId,selected.length]);for(const [position,key] of selected.entries())await client.query('INSERT INTO circle_amalan(circle_id,template_key,selected_by,position) VALUES($1,$2,$3,$4)',[circleId,key,userId,position]);await client.query(`INSERT INTO circle_activity(id,circle_id,actor_id,event_type,message) VALUES($1,$2,$3,'AMALAN_UPDATED',$4)`,[randomBytes(8).toString('hex'),circleId,userId,`Fokus amalan katalog diperbarui (${selected.length} pilihan).`])});return{success:true,amalanKeys:selected}
 }
 async addCustomCircleAmalan(userId:string,circleId:string,item:CircleCustomAmalan){await this.assertRole(userId,circleId,['OWNER']);const count=await this.db.query<any>('SELECT count(*)::int AS count FROM circle_amalan WHERE circle_id=$1 AND is_custom=true',[circleId]);if(Number(count.rows[0]?.count)>=6)throw new BadRequestException({code:'CUSTOM_AMALAN_LIMIT',message:'Maksimal enam custom amalan dalam satu Circle.'});const key=`custom-${randomBytes(8).toString('hex')}`,positionResult=await this.db.query<any>('SELECT coalesce(max(position),-1)+1 AS position FROM circle_amalan WHERE circle_id=$1',[circleId]),position=Number(positionResult.rows[0]?.position??0);await this.db.transaction(async client=>{await client.query('INSERT INTO circle_amalan(circle_id,template_key,selected_by,position,is_custom,title,note,period,kind,target_value,unit) VALUES($1,$2,$3,$4,true,$5,$6,$7,$8,$9,$10)',[circleId,key,userId,position,item.title.trim(),item.note.trim(),item.period,item.kind,item.target,item.unit?.trim()||null]);await client.query(`INSERT INTO circle_activity(id,circle_id,actor_id,event_type,message) VALUES($1,$2,$3,'AMALAN_UPDATED',$4)`,[randomBytes(8).toString('hex'),circleId,userId,`Custom amalan “${item.title.trim()}” ditambahkan.`])});return{success:true,key}}
 async removeCustomCircleAmalan(userId:string,circleId:string,key:string){await this.assertRole(userId,circleId,['OWNER']);const total=await this.db.query<any>('SELECT count(*)::int AS count FROM circle_amalan WHERE circle_id=$1',[circleId]);if(Number(total.rows[0]?.count)<=1)throw new BadRequestException({code:'CIRCLE_AMALAN_REQUIRED',message:'Circle harus memiliki setidaknya satu amalan.'});const result=await this.db.query('DELETE FROM circle_amalan WHERE circle_id=$1 AND template_key=$2 AND is_custom=true RETURNING template_key',[circleId,key]);if(!result.rowCount)throw new NotFoundException({code:'CUSTOM_AMALAN_NOT_FOUND',message:'Custom amalan tidak ditemukan.'});return{success:true}}
 async joinChallenge(userId:string,challengeId:string){const ch=await this.db.query('SELECT 1 FROM challenges WHERE id=$1',[challengeId]);if(!ch.rowCount)throw new NotFoundException({code:'CHALLENGE_NOT_FOUND',message:'Tantangan tidak ditemukan.'});await this.db.query(`INSERT INTO challenge_memberships(user_id,challenge_id,status) VALUES($1,$2,'ACTIVE') ON CONFLICT(user_id,challenge_id) DO UPDATE SET status='ACTIVE',paused_at=NULL`,[userId,challengeId]);return{success:true,challengeId}}
 async updateChallenge(userId:string,challengeId:string,status:string){if(status==='LEFT')await this.db.query(`UPDATE challenge_memberships SET status='LEFT' WHERE user_id=$1 AND challenge_id=$2`,[userId,challengeId]);else await this.db.query(`UPDATE challenge_memberships SET status=$3,paused_at=CASE WHEN $3='PAUSED' THEN now() ELSE NULL END WHERE user_id=$1 AND challenge_id=$2`,[userId,challengeId,status]);return{success:true,status}}
 async challengeCalendar(userId:string,challengeId:string){const key:Record<string,string>={'dhuha-30':'dhuha','quran-30':'quran','istighfar-30':'istighfar'},entryKey=key[challengeId];if(!entryKey)throw new NotFoundException({code:'CHALLENGE_NOT_FOUND',message:'Tantangan tidak ditemukan.'});const rows=await this.db.query<any>('SELECT local_date::text AS date,status FROM daily_entries WHERE user_id=$1 AND entry_key=$2 ORDER BY local_date DESC LIMIT 60',[userId,entryKey]);return rows.rows}
 async circleChallenge(userId:string,circleId:string){await this.assertMember(userId,circleId);const result=await this.db.query<any>(`SELECT cc.challenge_id,cc.status,cc.started_at,cc.completed_at,c.title,c.description,c.target_value,c.unit,c.icon,c.source_label,c.source_url FROM circle_challenges cc JOIN challenges c ON c.id=cc.challenge_id WHERE cc.circle_id=$1 AND cc.status<>'LEFT' ORDER BY cc.started_at DESC LIMIT 1`,[circleId]);if(!result.rowCount)return null;const row=result.rows[0],keys:Record<string,string>={'dhuha-30':'dhuha','quran-30':'quran','istighfar-30':'istighfar'},key=keys[row.challenge_id]||row.challenge_id;const progress=await this.db.query<any>(`SELECT count(DISTINCT d.local_date)::int AS active_days,count(*)::int AS contributions FROM daily_entries d JOIN circle_members m ON m.user_id=d.user_id AND m.circle_id=$1 AND m.status='ACTIVE' WHERE d.entry_key=$2 AND d.completed=true AND d.local_date>=($3::timestamptz AT TIME ZONE 'Asia/Jakarta')::date`,[circleId,key,row.started_at]);const target=Number(row.target_value??30),current=Math.min(Number(progress.rows[0]?.active_days??0),target);return{id:row.challenge_id,title:row.title,description:row.description,target,unit:row.unit,icon:row.icon,sourceLabel:row.source_label,sourceUrl:row.source_url,status:current>=target?'COMPLETED':row.status,current,contributions:Number(progress.rows[0]?.contributions??0),startedAt:row.started_at.toISOString()}}
 async startCircleChallenge(userId:string,circleId:string,challengeId:string){await this.assertRole(userId,circleId,['OWNER','ADMIN']);const templateResult=await this.db.query<any>('SELECT id,title,description,target_value,unit,icon,source_label,source_url FROM challenges WHERE id=$1',[challengeId]);if(!templateResult.rowCount)throw new NotFoundException({code:'CHALLENGE_NOT_FOUND',message:'Tantangan tidak ditemukan.'});const template=templateResult.rows[0];await this.db.transaction(async client=>{await client.query(`UPDATE circle_challenges SET status='LEFT' WHERE circle_id=$1 AND status='ACTIVE'`,[circleId]);await client.query(`INSERT INTO circle_challenges(circle_id,challenge_id,status,started_by,started_at,completed_at) VALUES($1,$2,'ACTIVE',$3,now(),NULL) ON CONFLICT(circle_id,challenge_id) DO UPDATE SET status='ACTIVE',started_by=excluded.started_by,started_at=now(),completed_at=NULL`,[circleId,challengeId,userId]);const amalanMap:Record<string,string>={'dhuha-30':'dhuha','quran-30':'quran','istighfar-30':'istighfar'},amalanKey=amalanMap[challengeId];if(amalanKey){const maxPos=await client.query<any>('SELECT coalesce(max(position),-1)+1 AS next_pos FROM circle_amalan WHERE circle_id=$1',[circleId]);await client.query(`INSERT INTO circle_amalan(circle_id,template_key,selected_by,position) VALUES($1,$2,$3,$4) ON CONFLICT(circle_id,template_key) DO NOTHING`,[circleId,amalanKey,userId,Number(maxPos.rows[0]?.next_pos??0)]);}await client.query(`INSERT INTO circle_activity(id,circle_id,actor_id,event_type,message) VALUES($1,$2,$3,'CHALLENGE',$4)`,[randomBytes(8).toString('hex'),circleId,userId,`Tantangan ${template.title} dimulai bersama.`])});return this.circleChallenge(userId,circleId)}
 async sendEncouragement(userId:string,circleId:string,key='continue'){await this.assertMember(userId,circleId);const encResult=await this.db.query<any>('SELECT message FROM encouragement_templates WHERE key=$1',[key]);const message=encResult.rows[0]?.message??encouragementMessages[key];if(!message)throw new BadRequestException({code:'ENCOURAGEMENT_INVALID',message:'Pilih pesan semangat yang tersedia.'});const [sender,circle]=await Promise.all([this.db.query<any>('SELECT display_name FROM users WHERE id=$1',[userId]),this.db.query<any>('SELECT name FROM circles WHERE id=$1',[circleId])]);const circleName=circle.rows[0]?.name??'Circle',senderName=sender.rows[0]?.display_name??'Teman Circle',idPrefix=randomBytes(8).toString('hex');const formattedMsg=`${senderName} (${circleName}): “${message}”`;const result=await this.db.query(`INSERT INTO notifications(id,user_id,title,message) SELECT $1||'-'||row_number() over()::text,m.user_id,'Semangat dari Circle',$2 FROM circle_members m JOIN users u ON u.id=m.user_id WHERE m.circle_id=$3 AND m.user_id<>$4 AND m.status='ACTIVE' AND COALESCE((u.notification_categories->>'circles')::boolean, true)=true RETURNING id`,[idPrefix,formattedMsg,circleId,userId]);await this.db.query('INSERT INTO circle_activity(id,circle_id,actor_id,event_type,message) VALUES($1,$2,$3,\'ENCOURAGEMENT\',$4)',[randomBytes(8).toString('hex'),circleId,userId,`${senderName} membagikan semangat: “${message}”`]);return{success:true,recipients:result.rowCount,message:result.rowCount?'Semangat berhasil dikirim.':'Belum ada anggota lain yang menerima semangat.'}}
 async getEncouragements(){const result=await this.db.query<any>('SELECT key,message FROM encouragement_templates ORDER BY key');return result.rows}
 async getMilestones(){const result=await this.db.query<any>('SELECT day,title,icon,description,reflection FROM journey_milestones ORDER BY day');return result.rows}
 async getCollectiveMilestones(){const result=await this.db.query<any>('SELECT level,title,desc_text,reflection FROM collective_milestones ORDER BY level');return result.rows.map(r=>({level:r.level,title:r.title,desc:r.desc_text,reflection:r.reflection}))}
 async createInvite(userId:string,circleId:string,input:{mode:string;maxUses:number;expiresInDays:number;approvalRequired:boolean}){await this.assertRole(userId,circleId,['OWNER','ADMIN']);const mode=input.mode,maxUses=mode==='PRIVATE'?1:input.maxUses,token=randomBytes(24).toString('base64url'),hash=createHash('sha256').update(token).digest('hex');await this.db.query(`INSERT INTO circle_invites(token_hash,circle_id,created_by,expires_at,mode,max_uses,approval_required) VALUES($1,$2,$3,now()+($4||' days')::interval,$5,$6,$7)`,[hash,circleId,userId,input.expiresInDays,mode,maxUses,input.approvalRequired]);return{expiresInDays:input.expiresInDays,mode,maxUses,inviteUrl:`${process.env.WEB_ORIGIN??'http://localhost:3001'}/invite/${token}`}}
 async getInvite(token:string){const hash=createHash('sha256').update(token).digest('hex'),result=await this.db.query<any>(`SELECT c.name,c.type,i.expires_at,i.mode,i.max_uses,i.use_count,i.approval_required FROM circle_invites i JOIN circles c ON c.id=i.circle_id WHERE i.token_hash=$1 AND i.expires_at>now() AND i.use_count<i.max_uses`,[hash]);if(!result.rowCount)throw new NotFoundException({code:'INVITE_NOT_FOUND',message:'Undangan tidak ditemukan, sudah penuh, atau kedaluwarsa.'});const row=result.rows[0];return{circleName:row.name,circleType:row.type,expiresAt:row.expires_at.toISOString(),mode:row.mode,remainingUses:row.max_uses-row.use_count,approvalRequired:row.approval_required}}
 async acceptInvite(userId:string,token:string){const hash=createHash('sha256').update(token).digest('hex');return this.db.transaction(async client=>{const invite=await client.query<any>(`SELECT i.circle_id,i.max_uses,i.use_count,i.approval_required,c.owner_id,c.name FROM circle_invites i JOIN circles c ON c.id=i.circle_id WHERE i.token_hash=$1 AND i.expires_at>now() AND i.use_count<i.max_uses FOR UPDATE`,[hash]);if(!invite.rowCount)throw new NotFoundException({code:'INVITE_NOT_FOUND',message:'Undangan tidak ditemukan, sudah penuh, atau kedaluwarsa.'});const row=invite.rows[0],status=row.approval_required?'PENDING':'ACTIVE';await client.query('INSERT INTO circle_members(circle_id,user_id,status) VALUES($1,$2,$3) ON CONFLICT(circle_id,user_id) DO UPDATE SET status=excluded.status',[row.circle_id,userId,status]);await client.query('UPDATE circle_invites SET use_count=use_count+1,used_at=CASE WHEN use_count+1>=max_uses THEN now() ELSE used_at END WHERE token_hash=$1',[hash]);const member=await client.query<any>('SELECT display_name FROM users WHERE id=$1',[userId]);if(row.owner_id!==userId)await client.query(`INSERT INTO notifications(id,user_id,title,message) SELECT $1,$2,$3,$4 FROM users u WHERE u.id=$2 AND COALESCE((u.notification_categories->>'circles')::boolean, true)=true`,[randomBytes(8).toString('hex'),row.owner_id,status==='PENDING'?'Permintaan bergabung':'Anggota baru',`${member.rows[0]?.display_name??'Anggota baru'} ${status==='PENDING'?'meminta bergabung ke':'bergabung ke'} ${row.name}.`]);return{success:true,circleId:row.circle_id,status}})}
 async updateMember(userId:string,circleId:string,memberId:string,action:'APPROVE'|'REMOVE'|'ADMIN'|'MEMBER'){await this.assertRole(userId,circleId,['OWNER','ADMIN']);const role=await this.role(userId,circleId);if(action==='ADMIN'&&role!=='OWNER')throw new ForbiddenException({code:'OWNER_REQUIRED',message:'Hanya Owner yang dapat menetapkan Admin.'});if(action==='APPROVE'){await this.db.query(`UPDATE circle_members SET status='ACTIVE' WHERE circle_id=$1 AND user_id=$2`,[circleId,memberId]);const circle=await this.db.query<any>('SELECT name FROM circles WHERE id=$1',[circleId]);const circleName=circle.rows[0]?.name??'Circle';await this.db.query(`INSERT INTO notifications(id,user_id,title,message) SELECT $1,$2,'Permintaan bergabung disetujui',$3 FROM users u WHERE u.id=$2 AND COALESCE((u.notification_categories->>'circles')::boolean, true)=true`,[randomBytes(8).toString('hex'),memberId,`Alhamdulillah, permintaan bergabungmu ke ${circleName} telah disetujui.`]);}else if(action==='REMOVE')await this.db.query('DELETE FROM circle_members WHERE circle_id=$1 AND user_id=$2 AND role<>\'OWNER\'',[circleId,memberId]);else await this.db.query('UPDATE circle_members SET role=$3 WHERE circle_id=$1 AND user_id=$2 AND role<>\'OWNER\'',[circleId,memberId,action]);return{success:true}}
 async leaveCircle(userId:string,circleId:string){const role=await this.role(userId,circleId);if(role==='OWNER')throw new BadRequestException({code:'TRANSFER_REQUIRED',message:'Transfer kepemilikan sebelum keluar dari Circle.'});await this.db.query('DELETE FROM circle_members WHERE circle_id=$1 AND user_id=$2',[circleId,userId]);return{success:true}}
 async transferOwnership(userId:string,circleId:string,memberId:string){await this.assertRole(userId,circleId,['OWNER']);await this.db.transaction(async client=>{await client.query(`UPDATE circle_members SET role='MEMBER' WHERE circle_id=$1 AND user_id=$2`,[circleId,userId]);const result=await client.query(`UPDATE circle_members SET role='OWNER' WHERE circle_id=$1 AND user_id=$2 AND status='ACTIVE' RETURNING user_id`,[circleId,memberId]);if(!result.rowCount)throw new NotFoundException({code:'MEMBER_NOT_FOUND',message:'Anggota tidak ditemukan.'});await client.query('UPDATE circles SET owner_id=$2 WHERE id=$1',[circleId,memberId])});return{success:true}}
 async archiveCircle(userId:string,circleId:string){await this.assertRole(userId,circleId,['OWNER']);await this.db.query('UPDATE circles SET archived_at=now() WHERE id=$1',[circleId]);return{success:true}}
 async markNotificationRead(userId:string,id:string){const result=await this.db.query('UPDATE notifications SET read=true WHERE id=$1 AND user_id=$2 RETURNING id',[id,userId]);if(!result.rowCount)throw new NotFoundException({code:'NOTIFICATION_NOT_FOUND',message:'Notifikasi tidak ditemukan.'});return{success:true}}
 async markAllNotificationsRead(userId:string){await this.db.query('UPDATE notifications SET read=true WHERE user_id=$1',[userId]);return{success:true}}
 async updatePrivacy(userId:string,visibility:string){await this.db.query('UPDATE users SET privacy_visibility=$2 WHERE id=$1',[userId,visibility]);return{success:true,visibility}}
 async updatePreferences(userId:string,input:{remindersEnabled:boolean;reducedMotion:boolean;quietStart?:string;quietEnd?:string;reminderNotifications?:boolean;circleNotifications?:boolean;milestoneNotifications?:boolean}){const categories={reminders:input.reminderNotifications??true,circles:input.circleNotifications??true,milestones:input.milestoneNotifications??true};await this.db.query('UPDATE users SET reminders_enabled=$2,reduced_motion=$3,quiet_start=$4::time,quiet_end=$5::time,notification_categories=$6::jsonb WHERE id=$1',[userId,input.remindersEnabled,input.reducedMotion,input.quietStart||null,input.quietEnd||null,JSON.stringify(categories)]);return{success:true,...input,categories}}
 private async role(userId:string,circleId:string){const result=await this.db.query<any>(`SELECT role FROM circle_members WHERE circle_id=$1 AND user_id=$2 AND status='ACTIVE'`,[circleId,userId]);if(!result.rowCount)throw new ForbiddenException({code:'CIRCLE_ACCESS_DENIED',message:'Kamu tidak memiliki akses ke Circle ini.'});return result.rows[0].role as string}
 private async assertMember(userId:string,circleId:string){await this.role(userId,circleId)}
 private async assertRole(userId:string,circleId:string,roles:string[]){const role=await this.role(userId,circleId);if(!roles.includes(role))throw new ForbiddenException({code:'CIRCLE_ROLE_REQUIRED',message:'Peranmu tidak memiliki izin untuk tindakan ini.'})}
 private assertTestingEnabled(){if(process.env.NODE_ENV==='production')throw new NotFoundException({code:'NOT_FOUND',message:'Endpoint tidak tersedia.'})}
 private async validAmalan(keys:string[]){const unique=[...new Set(keys)].slice(0,12);if(!unique.length)return[];const valid=await this.db.query<{key:string}>('SELECT key FROM amalan_templates WHERE key = ANY($1)',[unique]);const validSet=new Set(valid.rows.map(r=>r.key));return unique.filter(k=>validSet.has(k))}
}
